### ISSUE TITLE
appdef: projector: INCLUDING ERRORS

### ISSUE THREAD

**Issue by michael-say** [voedger/voedger#1024]
# Project is able to handle `sys.error` events

When true, projector is also feed with error events. False by default.
```sql
PROJECTOR CountOrders
  AFTER EXECUTE ON Orders
  INTENTS(View(OrdersCountView))
  INCLUDING ERRORS;
```

[Uncomment in parser](https://github.com/voedger/voedger/blob/133c8d1a5ced8cd2ee425faed955ebb3b823b3cc/pkg/parser/impl_build.go#L394C12-L394C12)

## TODO:

- Changes in `appdef.IProjector` interface
  - [x] add `WantErrors() bool`, false by default
- Changes in `appdef.IPorjectorBuilder` interface
  - [x] add `SetWantErrors(bool)`
- Changes in `parser.buildContext.projectors()`
  - [x] [Uncomment](https://github.com/voedger/voedger/blob/133c8d1a5ced8cd2ee425faed955ebb3b823b3cc/pkg/parser/impl_build.go#L394C12-L394C12)
- Other
  - [x] update `appdef\Readme.md`
  - [x] update `istructsmem\descr` package
