### ISSUE TITLE
Better naming

### ISSUE THREAD

**Issue by maxim-ge** [voedger/voedger#1168]
### General
- Do not use `-` in file names
- Do not separate name parts: Use `complexname_test.go`, not `complex_name_test.go` 

### Libraries: package with interfaces & implementations
- To implement interfaces, use `impl_*.go`: `interface_wdoc.go` ⇒ `impl_wdoc.go`

### Enumerations
- Declare enumeration constants near type declaration, do not use separate files. Only large (~20 items or more) enumerations can be moved to a separate file.
- Use prefix `stringer_` file outputs: `stringer_datakind.go`
```[tasklist]
### Tasks
- [ ] https://github.com/voedger/voedger/issues/1558
- [ ] https://github.com/voedger/voedger/issues/1854
- [ ] better naming: istructsmem/qname
- [ ] https://github.com/voedger/voedger/issues/3064
```
