### ISSUE TITLE
voedger cmd: eliminate grafana and prometheus ports wiring

### ISSUE THREAD

**Issue by host6** [voedger/voedger#1192]
```[tasklist]
### Tasks
- [ ] eliminate `GrafanaPort` and `PrometheusPort` types
- [ ] relocate `defaultGrafanaPort` and `defaultPrometheusPort` consts to `apps` package
- [ ] eliminate these ports from args of `wireServer()`
- [ ] `NewRedirectionRoutes()`: take ports from consts, not from args
```
