### ISSUE TITLE
AmazonDB Driver

### ISSUE THREAD

**Issue by maxim-ge** [voedger/voedger#1332]
## Motivation

- Aruba
- Do not want to create and support one more cassandra cluster

## Requirements

- ConsistentRead
Solution
- https://github.com/voedger/voedger/tree/main/pkg/istorage/dynamodb

## Context

- https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DynamoDBLocal.html
- https://github.com/voedger/voedger/tree/main/pkg/istorage
- https://github.com/voedger/voedger/tree/main/pkg/istorageimpl/istoragecas

```[tasklist]
### Tasks
- [x] https://github.com/voedger/voedger/issues/1333
- [ ] https://github.com/voedger/voedger/issues/1381
- [ ] https://github.com/voedger/voedger/issues/1385
- [ ] https://github.com/voedger/voedger/issues/1452
- [ ] https://github.com/voedger/voedger/issues/1453
- [x] https://github.com/voedger/voedger/issues/1454
```

**Comment by host6** [comment]
```
docker run -p 8000:8000 -e AWS_REGION=eu-west-1 -e AWS_ACCESS_KEY_ID=local -e AWS_SECRET_ACCESS_KEY=local amazon/dynamodb-local
```
