### ISSUE TITLE
[epic] Turn on linters for bp3/voedger

### ISSUE THREAD

**Issue by maxim-ge** [voedger/voedger#1366]
## Motivation

Improve project quality using linters

## Technical Design

- Add linters by small groups to avoid unexpected errors during PRs
- https://github.com/voedger/voedger/blob/main/.golangci.yml

```[tasklist]
### Tasks
- [ ] https://github.com/voedger/voedger/issues/1367
- [ ] https://github.com/voedger/voedger/issues/1368
- [ ] https://github.com/voedger/voedger/issues/1405
- [ ] https://github.com/voedger/voedger/issues/1402
- [ ] https://github.com/voedger/voedger/issues/1423
- [ ] https://github.com/voedger/voedger/issues/1426
- [ ] https://github.com/voedger/voedger/issues/1417
- [ ] https://github.com/voedger/voedger/issues/1418
- [ ] https://github.com/voedger/voedger/issues/1427
- [ ] https://github.com/voedger/voedger/issues/1446
- [ ] https://github.com/voedger/voedger/issues/2683
```
