### ISSUE TITLE
voedger: Use IAppParts instead of IAppStructsProvider. Step 3 - async projectors

### ISSUE THREAD

**Issue by mail2nnv** [voedger/voedger#1416]
This continues the issue #1315 

## Context

- [init](https://github.com/voedger/voedger/blob/4192a1c5159bfee8a80661c44ef2de69bc4384bc/pkg/projectors/async.go#L140)
- [DoAsync](https://github.com/voedger/voedger/blob/4192a1c5159bfee8a80661c44ef2de69bc4384bc/pkg/projectors/async.go#L407)

## TODO

- [ ] ~IState.SetAppStructsGetter(getter AppStructsFunc)~
- [ ] ~(p *asyncProjector) DoAsync calls SetAppStructsGetter()~
```[tasklist]
### TODO
- [x] store borrowed app partition into internal projector field and relase it after using
- [x] add projector method `borrowedAppStructs() IAppStructs`, that return AppStructs from borrowed partition or panic if no borrowed partition (or partition was released)
- [x] provide AppStructs to projector [state](https://github.com/voedger/voedger/blob/4192a1c5159bfee8a80661c44ef2de69bc4384bc/pkg/projectors/async.go#L191) via `borrowedAppStructs()` method
- [x] remove direct IAppStructs using from [asyncActualizer](https://github.com/voedger/voedger/blob/4192a1c5159bfee8a80661c44ef2de69bc4384bc/pkg/projectors/async.go#L58)
```
