### ISSUE TITLE
CSingleton & WSingleton

### ISSUE THREAD

**Issue by michael-say** [voedger/voedger#1469]
```sql
ABSTRACT TABLE CSingleton INHERITS CDoc();
ABSTRACT TABLE WSingleton INHERITS WDoc();

-- Deprecated, use CSingleton instead
ABSTRACT TABLE Singleton INHERITS CSingleton();
```

```[tasklist]
### Tasks
- [x] https://github.com/voedger/voedger/issues/1568
- [ ] https://github.com/voedger/voedger/issues/1607
- [ ] https://github.com/voedger/voedger/issues/1615
- [ ] https://github.com/voedger/voedger/issues/1628
- [ ] https://github.com/voedger/voedger/issues/1610
- [ ] https://github.com/voedger/voedger/issues/1715
```
