### ISSUE TITLE
[epic] (too many subtasks) ApplicationDevelopment

### ISSUE THREAD

**Issue by maxim-ge** [voedger/voedger#1474]
Too big issue. Closed, parts have been moved to the project https://github.com/orgs/voedger/projects/11/views/9

## Principles

- https://github.com/voedger/voedger/blob/main/design/services.md

```[tasklist]
### Tasks
- [ ] https://github.com/voedger/voedger/issues/1479
- [ ] https://github.com/voedger/voedger/issues/1502
- [ ] https://github.com/voedger/voedger/issues/1503
- [ ] https://github.com/voedger/voedger/issues/1509
- [ ] https://github.com/voedger/voedger/issues/1488
- [ ] https://github.com/voedger/voedger/issues/1529
- [ ] https://github.com/voedger/voedger/issues/1547
- [ ] https://github.com/voedger/voedger/issues/1559
- [ ] https://github.com/voedger/voedger/issues/1528
- [ ] https://github.com/voedger/voedger/issues/1540
- [ ] https://github.com/voedger/voedger/issues/1570
- [ ] https://github.com/voedger/voedger/issues/1697
- [ ] https://github.com/voedger/voedger/issues/1714
- [ ] https://github.com/voedger/voedger/issues/1836
- [x] importbo, legacy unTill schemas: migrate `*.sql` to `*.vsql`
- [ ] https://github.com/voedger/voedger/issues/1837
```

```[tasklist]
### Misc
- [ ] https://github.com/voedger/voedger/issues/1511
- [ ] https://github.com/voedger/voedger/issues/1522
```

```[tasklist]
### parser + appdef
- [ ] https://github.com/voedger/voedger/issues/1484
- [ ] https://github.com/voedger/voedger/issues/1500
- [ ] == state + intents
- [ ] https://github.com/voedger/voedger/issues/1523
- [ ] https://github.com/voedger/voedger/issues/1611
- [ ] https://github.com/voedger/voedger/issues/1671
- [ ] https://github.com/voedger/voedger/issues/1670
```

```[tasklist]
### WASM
- [ ] https://github.com/voedger/voedger/issues/1541
- [ ] https://github.com/voedger/voedger/issues/1645
- [ ] https://github.com/voedger/voedger/issues/1647
```
