### ISSUE TITLE
vpm gen orm (Pbill-related entities)

### ISSUE THREAD

**Issue by maxim-ge** [voedger/voedger#1490]
## Requirements

`vpm gen orm [--header_file]`

- header_file: path to file to insert as a header for every generated file

Process
- Parse
- Remove/create `internal/orm` folder (do not remove `internal` :) )
- Create orm structs for
  - Own workspaces: all non-abstract records (including inherited ones) + own commands/queries
  - Other workspaces: all own non-abstract records + own commands/queries
  - All referenced types from previous steps
- For every package create `package_<name>.go` 
- Default header???

### `package_<name>.go`  structure

- Sorted by type name

## Context

- https://github.com/voedger/voedger/blob/a7e6b09e1a3f80de8cc4280740be60cb8ba56232/examples/airs-bp/air/extwasm/main.go#L14
```[tasklist]
### Tasks
- [ ] https://github.com/voedger/voedger/issues/1801
- [ ] https://github.com/voedger/voedger/issues/1802
- [ ] https://github.com/voedger/voedger/issues/1805
- [ ] parser: store the initial sql code
- [ ] render the initial sql as the comment for generated go code
```
