### ISSUE TITLE
Describe Voedger/Air tables using Voedger SQL

### ISSUE THREAD

**Issue by maxim-ge** [voedger/voedger#167]
## Motivation

- Now we use so called "builders" to describe the Air data structures and `yaml` to describe the structures inherited from unTill 
- It works but sources are hard to read and maintain

See also

- [heeus.io: Draft SQL schema parser](https://dev.heeus.io/launchpad/#!26744)

Solution

- Describe all Air + unTill tables and views using Voedger SQL
Packages:
- [untill](https://github.com/untillpro/airs-scheme/blob/master/bp3/schema.sql)
- air
  - https://github.com/untillpro/airs-bp3/blob/main/packages/air/resellersubscriptionsprofile/schemas.sql
  - https://github.com/untillpro/airs-bp3/blob/main/packages/air/subscription/schemas.sql
  - https://github.com/untillpro/airs-bp3/blob/main/packages/air/untillpayments/schemas.sql
  - https://github.com/untillpro/airs-bp3/blob/main/packages/air/userprofile/schemas.sql
  - https://github.com/untillpro/airs-bp3/blob/main/packages/air/workspace/schemas.sql
  - https://github.com/untillpro/airs-bp3/blob/main/packages/air/xzreports/schemas.sql
- sys
  - https://github.com/voedger/voedger/blob/main/pkg/sys/authnz/signupin/schemas.sql
  - https://github.com/voedger/voedger/blob/main/pkg/sys/authnz/workspace/schemas.sql
  - https://github.com/voedger/voedger/blob/main/pkg/sys/authnz/schemas.sql
  - https://github.com/voedger/voedger/blob/main/pkg/sys/blobber/schemas.sql
  - https://github.com/voedger/voedger/blob/main/pkg/sys/invite/schemas.sql
  - https://github.com/voedger/voedger/blob/main/pkg/sys/sys.sql

## Unclear

- [x] How is existing yaml scheme processed?
  - Fields for nested  declaration were ignored (now they do not exist)
- [x] ODoc nested to ODoc?
  - [ODocs should be able to contain ODocs (Nested ODocs)](https://dev.heeus.io/launchpad/#!19332)

```[tasklist]
### Voedger
- [x] #98
- [x] #173
- [x] #174
- [x] #185
- [x] #207
- [x] #220
- [x] #238
- [ ] https://github.com/voedger/voedger/issues/286
- [ ] https://github.com/voedger/voedger/issues/287
- [ ] #237
- [ ] https://github.com/voedger/voedger/issues/375
- [ ] https://github.com/voedger/voedger/issues/520
- [ ] https://github.com/voedger/voedger/issues/522
- [ ] https://github.com/voedger/voedger/issues/524
- [ ] https://github.com/voedger/voedger/issues/517
- [ ] https://github.com/voedger/voedger/issues/545
- [ ] https://github.com/voedger/voedger/issues/574
- [ ] https://github.com/voedger/voedger/issues/564
- [ ] https://github.com/voedger/voedger/issues/581
- [ ] https://github.com/voedger/voedger/issues/582
- [ ] https://github.com/voedger/voedger/issues/594
- [ ] https://github.com/voedger/voedger/issues/598
- [ ] https://github.com/voedger/voedger/issues/603
```

```[tasklist]
### voedger: reference targets
- [x] #169
- [x] #171
- [x] #172
- [ ] #236
- [ ] https://github.com/voedger/voedger/issues/373
- [ ] https://github.com/voedger/voedger/issues/566
```

```[tasklist]
### Air
- [x] #170
- [x] #199
- [x] untillpro/air-importbo#17
- [x] untillpro/air-importbo/issues/23
- [x] untillpro/air-importbo#21
- [x] untillpro/air-importbo#25
- [x] untillpro/airs-scheme#9
- [ ] https://github.com/voedger/voedger/issues/273
- [ ] https://github.com/voedger/voedger/issues/332
- [ ] https://github.com/voedger/voedger/issues/331
- [ ] https://github.com/voedger/voedger/issues/604
- [ ] https://github.com/voedger/voedger/issues/605
```

```[tasklist]
### Misc
- [ ] https://github.com/voedger/voedger/issues/579
```

**Comment by host6** [comment]
impossible to use .sql in bp3 because the .sql is located at an another repository
