### ISSUE TITLE
Voedger Type System

### ISSUE THREAD

**Issue by maxim-ge** [voedger/voedger#168]
## Pain

We do not have a clean type system description

### Principles

- *Commands and Queries*. Arguments and results of commands and queries may be arrays. *Now:* only `ODoc` document allowed.
- *Arrays in structs*. Structure fields may be arrays. *Now:* only simple data types allowed.
- *Functions*. Simple data types (and arrays) for functions in/out parameters. *Now:* only structs allowed.
- *User data types*. User can declare custom data kinds, inherits from system or other user data kinds. *Now:* only system data kinds allowed.
- *Anonymous types*. Some parts of structures definition can include unnamed user types (e.g. `array[10] sys.float64`). *Now:* all definitions must have names.
- *Avoiding the surprises of duck typing*. To avoid unwanted type assertion some types may have non-exported stub method like `isObject()`, `isCRecord()` etc.

### Types: inheritance

Ref to [READ.ME](https://github.com/voedger/voedger/blob/main/pkg/appdef/README.md):
- [Type inheritance](https://github.com/voedger/voedger/blob/main/pkg/appdef/README.md#types-inheritance)
- [Type composing](https://github.com/voedger/voedger/blob/main/pkg/appdef/README.md#types-composing)

### Field

<details><summary>Mermaid Class Diagram </summary>
<p>

#### Field

```mermaid
classDiagram
    class IField {
        <<interface>>
        +Name() string
        +Type() IType
        +Constrains() []IConstrain 
        +Verification() []VerificationKind
    }

    IRefField <-- IField : may be
    class IRefField {
        <<interface>>
        TypeKind_Data
        DataKind_RecordID
        +Refs() []QName
    }

    IStringField <-- IField : may be
    class IStringField {
        <<interface>>
        TypeKind_Data
        DataKind_String
    }

    IBytesField <-- IField : may be
    class IBytesField {
        <<interface>>
        TypeKind_Data
        DataKind_Bytes
    }

    INumberField <-- IField : may be
    class INumberField {
        <<interface>>
        TypeKind_Data
        DataKind_Int32
        DataKind_Int64
        DataKind_Float32
        ...
    }

    IArrayField <-- IField : may be
    class IArrayField {
        <<interface>>
        TypeKind_Array
        Elem() IType
    }
    IArrayField ..> IType : has element


    IField "1" *--> "0..*" IConstrain : may be constrained
    class IConstrain {
        <<interface>>
        Kind() IRestringKind
        Value() interface
    }

    IConstrain *--> ConstrainKind : has kind
    class ConstrainKind {
        <<enumeration>>
        MinLength
        MaxLength
        Pattern
        MinExclusive
        MaxExclusive
        MinInclusive
        MaxInclusive
        ...
    }

    IField ..> IType : has type
    class IType{
        <<interface>>
    }

    IType --> IData : may be
    class IData {
        <<interface>>
        Kind() DataKind
        Ancestor() IData
    }
    IData ..> IData : refs to ancestor

    IData *--> DataKind : has kind
    class DataKind {
        <<enumeration>>
        Int32
        Int64
        Float32
        Float64
        String
        Bytes
        QName
        RecordID
        ...
    }

    IType --> IArray : may be
    class IArray {
        <<interface>>
        Elem() IType
    }
    IArray ..> IData : refs to type
```

</p>
</details> 

### Container

<details><summary>Mermaid Class Diagram </summary>
<p>

#### Container

```mermaid
classDiagram
    direction TB
    class IStructure {
        +Containers() []IContainer
    }
    IStructure "1" *--> "0..*" IContainer
    class IContainer {
        <<interface>>
        +Name() string
        +QName() QName
        +MinOccurs() uint
        +MaxOccurs() uint
    }

    IContainer *-->QName
    QName ..> IStructure : refs to contained \n structure

```

#### Container composing illustrate by CDoc

```mermaid
classDiagram
    class ICDoc {
        <<interface>>
        +Containers() []IContainer
    }
    ICDoc "1" ..> "0..*" ICRecord : refs from\n Containers()

    class ICRecord {
        <<interface>>
        +Containers() []IContainer
    }
    ICRecord "1" ..> "0..*" ICRecord : refs from\n Containers()
```
</p>
</details> 

```[tasklist]
### TODO
- [ ] https://github.com/voedger/voedger/issues/671
- [ ] https://github.com/voedger/voedger/issues/689
- [ ] https://github.com/voedger/voedger/issues/709
- [ ] https://github.com/voedger/voedger/issues/735
- [ ] https://github.com/voedger/voedger/issues/750
- [ ] https://github.com/voedger/voedger/issues/759
```

**Comment by mail2nnv** [comment]
# Solution 2. Integrate `DataKind` into new `DefKind` member

- [ ] New `DefKind_Data` enumeration element
  - [ ] New `IData` interface inherits from `IDef` with members:
    - `Kind() DataKind`
    - `Ancestor() IData`. Ancestor data is nil for system definitions and not nil for user
    - `Restricts() []IRestrict`. System data has no restricts
  - [ ] New `IDataBuilder` interface with methods:
    - `Restrict(...IRestrict)`. If some taken restrict defined in ancestor, then it overrides ancestor restrict

- [ ] New system definitions for all simple data kinds must be added:
  - [ ] `Int32() IData`
  - [ ] `String() IData`
  - [ ] …
  - [ ] `SysData(DataKind) IData`

- [ ] Existing `IField` interface must be refactored:
  - [ ] new member `Data() IData` must be added,
  - [ ] existing member `DataKind() DataKind` must be deprecated

- [ ] Existing `IFieldsBuilder` interface must be refactored:
  - [ ] existing `AddField(… DataKind …)` and `AddVerifiedField(… DataKind …)` methods must be changed to takes `IData` (or, better, data definition `QName`) instead `DataKind`
  - [ ] existing `AddRefField()`, `AddStringField()` and other kind-specified field constructors must call general `AddField()` method and pass to it system data definitions. If some restricts are passed to these methods, then the anonymous data definition (with no `QName` and inherits from system) must be created under hood and passed to `AddField()`.

- [ ] `IAppDef` interface changes:
  - [ ] new `Data(QName) IData` method

- [ ] `IAppDefBuilder` interface changes:
  - [ ] new `AddData(name QName, ancestor IData, restricts ...IRestrict) IDataBuilder` method

**Comment by mail2nnv** [comment]
# Arrays in `istructs` row interfaces

## One-dimensional arrays

```golang
type IRowWriter interface {
  …
  // Puts value by index to specified array field
  PutInt32ToArray(name string, index uint, value int32)

  // Puts values array to specified array field
  PutInt32Array(name string, values []int32)
  …
}

type IRowReader interface {
  …
  // Gets value by index from specified array field
  AsInt32FromArray(name string, index uint) int32

  // Gets values array from specified array field
  AsInt32Array(name string) []int32
  …
}
```
