### ISSUE TITLE
archive: Migrate to IAppPartitions

### ISSUE THREAD

**Issue by maxim-ge** [voedger/voedger#1681]
```[tasklist]
### Tasks
- [ ] https://github.com/voedger/voedger/issues/661
- [x] https://github.com/voedger/voedger/issues/943
- [ ] https://github.com/voedger/voedger/issues/797
- [x] https://github.com/voedger/voedger/issues/1014
- [ ] https://github.com/voedger/voedger/issues/1054
- [x] https://github.com/voedger/voedger/issues/1055
- [ ] https://github.com/voedger/voedger/issues/1133
- [ ] https://github.com/voedger/voedger/issues/1135
- [ ] https://github.com/voedger/voedger/issues/1191
- [ ] https://github.com/voedger/voedger/issues/1189
- [ ] https://github.com/untillpro/airs-bp3/pull/862
- [ ] https://github.com/voedger/voedger/issues/1327
- [ ] https://github.com/voedger/voedger/issues/1357
- [ ] https://github.com/voedger/voedger/issues/1315
- [ ] https://github.com/voedger/voedger/issues/1432
- [ ] https://github.com/voedger/voedger/issues/1519
- [ ] https://github.com/voedger/voedger/issues/1350
- [ ] https://github.com/voedger/voedger/issues/1468
- [ ] https://github.com/voedger/voedger/issues/1493
- [ ] https://github.com/voedger/voedger/issues/1588
- [ ] https://github.com/voedger/voedger/issues/1584
- [ ] https://github.com/voedger/voedger/issues/1651
- [ ] https://github.com/voedger/voedger/issues/1653
```
