### ISSUE TITLE
[epic] ctool: install CE

### ISSUE THREAD

**Issue by maxim-ge** [voedger/voedger#1775]
## Requirements

- 1 node
- db: scylla

## Functional design

- `ctool init CE <local-node-address>`
  - `<local-node-address>` is a must since the node can have few network interfaces and the local one must be used
- `ctool upgrade`
- `ctool backup *`
- `ctool restore *`

## Technical design

Principles
- One compose file
- Services names
  - voedeger_voedger
  - voedeger_grafana
  - voedeger_prometheus
  - voedeger_alertmanager
  - voedeger_scylla
- `VOEDGER_STORAGE_TYPE=cas1 | cas3`

```[tasklist]
### Tasks
- [ ] https://github.com/voedger/voedger/issues/1776
- [ ] https://github.com/voedger/voedger/issues/1905
- [ ] https://github.com/voedger/voedger/issues/2019
- [ ] https://github.com/voedger/voedger/issues/2033
- [ ] https://github.com/voedger/voedger/issues/2047
- [ ] https://github.com/voedger/voedger/issues/2192
- [ ] https://github.com/voedger/voedger/issues/2193
- [ ] https://github.com/voedger/voedger/issues/2237
- [ ] https://github.com/voedger/voedger/issues/2034
```

```[tasklist]
### Tasks
- [ ] https://github.com/voedger/voedger/issues/2150
```
