### ISSUE TITLE
Jobs

### ISSUE THREAD

**Issue by maxim-ge** [voedger/voedger#1777]
## Motivation

- Run periodic tasks, e.g. to send daliy sales reports somewhere (it is necessary to obtain a French certification for the Air).

## Internals

- [server/jobs.md](https://github.com/voedger/voedger-internals/blob/main/server/jobs.md) 

## TODO

- IActualizers => IPartitionProcessors
- appPartitionRT
- what about missed firings? E.g. billing job that must charge the subscription fee on 1st of each month:
  - `0 0 1 * *`
  - now is 23:00:00 31th Dec
  - the next firing is schedued on 00:00 1st Jan
  - the PC is turned off on 23:50 31th Dec
  - the PC is turned on on 00:10 on 1st Jan
  - the timer is charged to be fired on 00:00 1st Feb
  - result -> firing on 1st Jan is missed, January is not processed by billing
- should a job be able to insert to view? (currently not, VSQL demands a projector name after `AS RESULT OF` clause in view definition)
- job is defined -> 10 app workspaces -> one job fired 10 times?
- would be good to have a certain job config, e.g. read job settings from somewhere on job start etc
  - e.g. need to write a doc, where to to call c.sys.CUD? Which WSID?
```[tasklist]
### Tasks
- [ ] https://github.com/voedger/voedger/issues/2648
- [ ] https://github.com/voedger/voedger/issues/1786
- [ ] https://github.com/voedger/voedger/issues/1892
- [ ] https://github.com/voedger/voedger/issues/1908
- [ ] https://github.com/voedger/voedger/issues/1897
- [ ] https://github.com/voedger/voedger/issues/2428
- [ ] https://github.com/voedger/voedger/issues/2433
- [ ] https://github.com/voedger/voedger/issues/2436
- [ ] https://github.com/voedger/voedger/issues/2437
- [ ] https://github.com/voedger/voedger/issues/2427
- [ ] https://github.com/voedger/voedger/issues/2518
- [ ] https://github.com/voedger/voedger/issues/2520
- [ ] https://github.com/voedger/voedger/issues/2459
- [ ] https://github.com/voedger/voedger/issues/2568
- [ ] https://github.com/voedger/voedger/issues/2557
- [ ] https://github.com/voedger/voedger/issues/2571
- [ ] https://github.com/voedger/voedger/issues/2577
- [ ] https://github.com/voedger/voedger/issues/2804
- [ ] https://github.com/voedger/voedger/issues/2552
- [ ] https://github.com/voedger/voedger/issues/2809
- [ ] https://github.com/voedger/voedger/issues/2810
```

```[tasklist]
### ➕
- [ ] https://github.com/voedger/voedger/issues/1916
```

**Comment by michael-say** [comment]
@maxim-ge should the declared scheduled projector be ran in every app partition? How does the actualizer knows which workspace(s) it is working with? We do not have a PLog entry in case of scheduled projector to indicate the WSID.

**Comment by mail2nnv** [comment]
```[tasklist]
### + tasks
- [ ] update `appdef/readme.md`
```
