### ISSUE TITLE
engines: shall be one factory per engine kind

### ISSUE THREAD

**Issue by maxim-ge** [voedger/voedger#1781]
Depends on #1780 #1797 

Problems

- ap.ApplyInitializeWorkspace needs per app
  - callback
  - templates
- ap.ApplyDeactivateWorkspace uses IStructsProvider (#1806)

```[tasklist]
### Tasks
- [x] apparts.NewWithActualizerWithExtEnginesFactories: should pass ExtensionEngineFactories, but notExtensionEngineFactoriesFactory
- [x] vvm.engines.ExtEngineFactoriesConfig.AppConfigs
- [x] iextengine.IExtensionEngineFactory.New() should pass appQName + packages, not only packages
- [x] iextengine.BuiltInExtFuncs: add application layer
- [x] iextengine.Provide: use new BuiltInExtFuncs
```
