### ISSUE TITLE
Deploy Application

### ISSUE THREAD

**Issue by maxim-ge** [voedger/voedger#1814]
## Internals

[server/clusters/deploy-app.md](https://github.com/voedger/voedger-internals/blob/main/server/clusters/deploy-app.md)

```[tasklist]
### Tasks
- [ ] https://github.com/voedger/voedger/issues/1890
- [ ] https://github.com/voedger/voedger/issues/1815
- [ ] https://github.com/voedger/voedger/issues/1816
- [ ] https://github.com/voedger/voedger/issues/2199
- [ ] https://github.com/voedger/voedger/issues/2274
- [ ] https://github.com/voedger/voedger/issues/2287
```
