### ISSUE TITLE
vpm init,tidy: improvements

### ISSUE THREAD

**Issue by maxim-ge** [voedger/voedger#1821]
```[tasklist]
### Tasks
- [x] use stderr always and stdout on verbose on PipedExec like `go get` (now nils are provided to Run())
- [x] initGlobalFlags(): move to main() as rootCmd.PersistentFlags()
- [x] eliminate `C` flag duplicate in tidy, init cmds
- [x] init: do not check `len(args)` in `RunE()`, provide `params.Dir` to initPackage()` instead
- [x] init: conflict with `C` flag and `args[0]` - the last one is considered as name of the module but could be `C` flag
- [x] init shall require go 1.22.2
```
