### ISSUE TITLE
VSQL Types

### ISSUE THREAD

**Issue by maxim-ge** [voedger/voedger#1829]
## Motivation

- Now we use such types unfamiliar to SQL developers as int32, int64.
- Need to prepare the documentation

## Proposal

- It shall be possible to use SQL-2016 types
- We can introduce aliases, like [postgresql](https://www.postgresql.org/docs/current/datatype.html): 
  - integer: int, int32
  - bigint: int64

### [SQL-92](https://www.contrib.andrew.cmu.edu/~shadow/sql/sql1992.txt)

> SQL defines distinct data types named by the following <key word>s:CHARACTER, CHARACTER VARYING, BIT, BIT VARYING, NUMERIC, DECIMAL, INTEGER, SMALLINT, FLOAT, REAL, DOUBLE PRECISION, DATE, TIME, TIMESTAMP, and INTERVAL.

### [SQL:2016 or ISO/IEC 9075-2:2016](http://www.sai.msu.su/~megera/postgres/files/sql-2016-json.txt):

```
SQL defines predefined data types named by the following <key word>s:
     CHARACTER
     CHARACTER VARYING
     CHARACTER LARGE OBJECT
     BINARY
     BINARY VARYING
     BINARY LARGE OBJECT
     NUMERIC
     DECIMAL
     SMALLINT
     INTEGER
     BIGINT
     FLOAT
     REAL
     DOUBLE PRECISION
     DECFLOAT
     BOOLEAN
     DATE
     TIME
     TIMESTAMP
     INTERVAL
```

### [postgresql, Data Types](https://www.postgresql.org/docs/current/datatype.html)

> Compatibility
> The following types (or spellings thereof) are specified by SQL: bigint, bit, bit varying, boolean, char, character varying, character, varchar, date, double precision, integer, interval, numeric, decimal, real, smallint, time (with or without time zone), timestamp (with or without time zone), xml.

### Functional Design

??? Need a table here

```[tasklist]
### Tasks
- [ ] https://github.com/voedger/voedger/issues/2015
- [ ] https://github.com/voedger/voedger/issues/2035
- [ ] voedger???
- [ ] bp3???
- [ ] https://github.com/voedger/voedger/issues/2098
```

**Comment by michael-say** [comment]
@maxim-ge https://github.com/voedger/voedger/blob/main/pkg/parser/README.md
