### ISSUE TITLE
[epic] vpm: fix review notes

### ISSUE THREAD

**Issue by maxim-ge** [voedger/voedger#1849]
```[tasklist]
### Tasks
- [ ] https://github.com/voedger/voedger/issues/1909
- [ ] https://github.com/voedger/voedger/issues/1852
- [ ] https://github.com/voedger/voedger/issues/1850
- [ ] https://github.com/voedger/voedger/issues/1851
```
