### ISSUE TITLE
App Partitions problem

### ISSUE THREAD

**Issue by maxim-ge** [voedger/voedger#1858]
## Motivation

Now it depends on processor number
- https://github.com/voedger/voedger/blob/c82e6c2ae8cbec573a77d1e9665ce2c225927683/pkg/utils/utils.go#L59

Has to be: application partition number

### Overall
- sys/router app
  - partsCount 10, cpCount 0, qpCount 0, actualizers 10
- sys/blobber app
  - partsCount 10, cpCount 10, qpCount 10, actualizers 10
- sys/registry, untill/airs-bp
  - partsCount VVM.CommandProcesorsCount, cpCount VVM.CommandProcesorsCount, qpCount 10, actualizers VVM.CommandProcesorsCount
- VVM.CommandProcessorsCount:
  - live - 100
  - test - 10
  - dev - 10
### VVM App Workspaces initialization
- partition is not recovered like on the first request to the partition! Just an event with CUD WSDesc is written to the partition
- partitionNum = appWSID % VVM.CommandProcesorsCount!!!

### Impact on Dev, Test
all apps are ok, theirs partsCount=VVM.CommandProcesorsCount

#### untill/airs-bp, sys/registry
ok becuase theirs partsCount=VVM.CommandProcesorsCount
#### sys/router, sys/blobber
bad because theirs partsCount (10) != VVM.CommandProcesorsCount(100 in Live) -> events with WSDesc CUDs are stored in wrong partitions

what if partitonsNum on AppWS init will be computed as `appWSID % app.DeploymentDescriptor.PartsCount`?
  - all AppWSID will be still considered as already inited because WSDescs are quired from AppWSID, not from a partition
  - any event in any AppWS (no such scenarious for now) -> big problem
    - partition of the event differs from partitin computed on AppWS init
    - CP partition recovery 
      - goes through PLog
      - no events in the PLog (because WSDesc CUD event is stored in an another partition) -> next PLogOffset, WLogOffset and RecordID are 1
      - the new event is written into PLog -> ok, just the first event is the partition
      - the new event is written into WLog -> the existing AppWSDesc CUD event is overwritten under offset 1
## Conclusion
- everything looks safe because data is not stored in storages of these apps except `cdoc.sys.WorkspaceDescriptor` of AppWorkspaces. 
- avoid any func in app workspaces of `sys/blobber` and `sys/router` on Live if `wsid % app's total amount of partitions`

```[tasklist]
### Tasks
- [ ] https://github.com/voedger/voedger/issues/1860
- [ ] https://github.com/voedger/voedger/issues/1859
- [ ] https://github.com/voedger/voedger/issues/1868
- [ ] https://github.com/voedger/voedger/issues/1869
- [ ] https://github.com/voedger/voedger/issues/1888
- [ ] https://github.com/voedger/voedger/issues/1898
- [ ] https://github.com/voedger/voedger/issues/1900
```

```[tasklist]
### Depends on
- [ ] https://github.com/voedger/voedger/issues/1890
```
