### ISSUE TITLE
[epic] Migrate design and architecture to internals.voedger.io

### ISSUE THREAD

**Issue by maxim-ge** [voedger/voedger#1872]
## Motivation

- It is not convinient to keep documentation in issues
  - Multiple issues can affect same feature
  - It is hard to work with a structured document
  - It is hard to work with mermaid
  - ++ Natural feature ID (issue number)
- It is not convinient to keep documentation in a repo
  - qs every time
  - Hard to search
  - Hard to navigate
  - No natural feature ID

## Solution

- https://internals.voedger.io
- https://internals.voedger.io/server/api-gateway
- Feature ID
  - concepts/uniques-multi
  - services-dev/vpm/init
- !!! todo/update-features
- !!! [## Internals section](https://github.com/voedger/voedger/issues/1777)
- !!! Remove from  voedger repo https://github.com/voedger/voedger/issues/1647

```[tasklist]
### Tasks
- [ ] https://github.com/voedger/voedger/issues/1875
- [ ] https://github.com/voedger/voedger/issues/1873
- [ ] https://github.com/voedger/voedger/issues/1958
```
