### ISSUE TITLE
[epic] cluster: bootstrap

### ISSUE THREAD

**Issue by maxim-ge** [voedger/voedger#1890]
## Internals

- [clusters/bootstrap](https://github.com/voedger/voedger-internals/blob/main/concepts/clusters/bootstrap.md)
```[tasklist]
### Tasks
- [ ] https://github.com/voedger/voedger/issues/1946
- [ ] https://github.com/voedger/voedger/issues/1964
- [ ] https://github.com/voedger/voedger/issues/1927
- [ ] https://github.com/voedger/voedger/issues/1976
- [ ] https://github.com/voedger/voedger/issues/1986
- [ ] https://github.com/voedger/voedger/issues/1978
- [ ] https://github.com/voedger/voedger/issues/2005
```
