### ISSUE TITLE
vpm: first light

### ISSUE THREAD

**Issue by maxim-ge** [voedger/voedger#1919]
```[tasklist]
### Tasks
- [ ] https://github.com/voedger/voedger/issues/1490
- [ ] https://github.com/voedger/voedger/issues/1791
- [ ] https://github.com/voedger/voedger/issues/1835
- [ ] https://github.com/voedger/voedger/issues/1969
- [ ] https://github.com/voedger/voedger/issues/2260
```

```[tasklist]
### Tasks
```
