### ISSUE TITLE
Develop applications (WASM Development etc.)

### ISSUE THREAD

**Issue by maxim-ge** [voedger/voedger#1920]
```[tasklist]
### Tasks
- [ ] https://github.com/voedger/voedger/issues/2669
- [ ] https://github.com/voedger/voedger/issues/2694
- [ ] https://github.com/voedger/voedger/issues/2699
```

```[tasklist]
### Done
- [ ] https://github.com/voedger/voedger/issues/2635
- [ ] https://github.com/voedger/voedger/issues/2619
- [ ] https://github.com/voedger/voedger/issues/2633
- [ ] https://github.com/voedger/voedger/issues/2564
- [ ] https://github.com/voedger/voedger/issues/2593
- [ ] https://github.com/voedger/voedger/issues/2599
- [ ] https://github.com/voedger/voedger/issues/2602
- [ ] https://github.com/voedger/voedger/issues/2591
- [ ] https://github.com/voedger/voedger/issues/2580
- [ ] https://github.com/voedger/voedger/issues/2589
- [ ] https://github.com/voedger/voedger/issues/2570
- [ ] https://github.com/voedger/voedger/issues/2448
- [ ] https://github.com/voedger/voedger/issues/2546
- [ ] https://github.com/voedger/voedger/issues/2181
- [ ] https://github.com/voedger/voedger/issues/2208
- [ ] https://github.com/voedger/voedger/issues/2231
- [ ] https://github.com/voedger/voedger/issues/2063
- [ ] https://github.com/voedger/voedger/issues/2186
- [ ] https://github.com/voedger/voedger/issues/2165
- [ ] https://github.com/voedger/voedger/issues/2065
- [ ] https://github.com/voedger/voedger/issues/2249
- [ ] https://github.com/voedger/voedger/issues/2233
- [ ] https://github.com/voedger/voedger/issues/2184
- [ ] https://github.com/voedger/voedger/issues/2183
- [ ] https://github.com/voedger/voedger/issues/2224
- [ ] https://github.com/voedger/voedger/issues/2245
- [ ] https://github.com/voedger/voedger/issues/2225
- [ ] https://github.com/voedger/voedger/issues/2185
- [ ] https://github.com/voedger/voedger/issues/1937
- [ ] https://github.com/voedger/voedger/issues/2329
- [ ] https://github.com/voedger/voedger/issues/2288
- [ ] https://github.com/voedger/voedger/issues/2275
- [ ] https://github.com/voedger/voedger/issues/2267
- [ ] https://github.com/voedger/voedger/issues/1935
- [ ] https://github.com/voedger/voedger/issues/1936
- [ ] https://github.com/voedger/voedger/issues/1957
- [ ] https://github.com/voedger/voedger/issues/1963
- [ ] https://github.com/voedger/voedger/issues/2095
- [ ] https://github.com/voedger/voedger/issues/1965
- [ ] https://github.com/voedger/voedger/issues/2122
- [ ] https://github.com/voedger/voedger/issues/2125
- [ ] https://github.com/voedger/voedger/issues/1997
- [ ] https://github.com/voedger/voedger/issues/2066
- [ ] https://github.com/voedger/voedger/issues/2040
- [ ] https://github.com/voedger/voedger/issues/2057
- [ ] https://github.com/voedger/voedger/issues/2077
- [ ] https://github.com/voedger/voedger/issues/2076
- [ ] https://github.com/voedger/voedger/issues/1973
- [ ] https://github.com/voedger/voedger/issues/1677
- [ ] https://github.com/voedger/voedger/issues/2094
- [ ] https://github.com/voedger/voedger/issues/2235
- [ ] https://github.com/voedger/voedger/issues/1949
- [ ] https://github.com/voedger/voedger/issues/2343
- [ ] https://github.com/voedger/voedger/issues/2123
- [ ] https://github.com/voedger/voedger/issues/2133
- [ ] https://github.com/voedger/voedger/issues/2135
- [ ] https://github.com/voedger/voedger/issues/2137
- [ ] https://github.com/voedger/voedger/issues/2143
- [ ] https://github.com/voedger/voedger/issues/2145
- [ ] ————————
- [ ] https://github.com/voedger/voedger/issues/2153
- [ ] https://github.com/voedger/voedger/issues/2160
- [ ] https://github.com/voedger/voedger/issues/2163
- [ ] ————————
- [ ] https://github.com/voedger/voedger/issues/2154
- [ ] https://github.com/voedger/voedger/issues/2167
- [ ] https://github.com/voedger/voedger/issues/2173
- [ ] https://github.com/voedger/voedger/issues/2180
```

**Comment by maxim-ge** [comment]
Closed in favor of smaller epics, e.g. #2742
