### ISSUE TITLE
examples/airs-bp2: test for Pbill 

### ISSUE THREAD

**Issue by maxim-ge** [voedger/voedger#1945]
## Requirements

- New example: airs-bp2

It shall be possible:

- vpm orm
- `go test`
- `vpm build`

## TODO

- [x] Add airs-bp2/orm to .gitignore
- [x] Copy main.go,  air.vsql from airs-bp/air to airs-bp2
- [ ] Develop main_test.go, ref. [examples](https://github.com/voedger/voedger-internals/blob/main/framework/api-testing.md)
- [x] orm: separate NewIntent method of the WSingletone into 2 variants: one for new value and 2nd one for update

## Context

- https://github.com/michael-say/voedger/blob/3834431aea4b7ac3ce503a56d3f995548dbf84d1/pkg/parser/impl_test.go#L446

**Comment by host6** [comment]
- Insert(rawID int)
- Containers - how to insert? 
- Get() result
  - add Update(), Insert()
  - found -> panic on Insert()
  - not found -> panic on field read and on Update()
