### ISSUE TITLE
Increase rate limits temporarily

### ISSUE THREAD

**Issue by maxim-ge** [voedger/voedger#2023]
## Motivation

Debug Air
```[tasklist]
### Tasks
- [ ] https://github.com/voedger/voedger/issues/2024
- [ ] https://github.com/voedger/voedger/issues/2027
- [ ] https://github.com/voedger/voedger/issues/2089
- [ ] https://github.com/voedger/voedger/issues/2090
```
