### ISSUE TITLE
eliminate deprecated dependencies

### ISSUE THREAD

**Issue by host6** [voedger/voedger#2083]
## Motivation

**Now, in current architecture**
following (but not exhausting) dependencies are used in few places:
- github.com/untillpro/airs-ibus
- github.com/untillpro/airs-ibusnats
- github.com/untillpro/ibusmem
- github.com/untillpro/goutils 
see also #1969

- Problem (warm): deprecated, according actual dependencies must be used

```[tasklist]
### Tasks
- [ ] https://github.com/voedger/voedger/issues/2485
- [ ] https://github.com/voedger/voedger/issues/2486
- [x] https://dev.untill.com/projects/#!704137
- [ ] https://github.com/voedger/voedger/issues/2727
```
