### ISSUE TITLE
update corrupted: istructs: IDbEvent.Bytes()

### ISSUE THREAD

**Issue by mail2nnv** [voedger/voedger#2112]
```[tasklist]
### Tasks
- [x] istructs: IDbEvent.Bytes()
- [x] istructsmem: support store original event bytes for sys.Corrupted event in IDbEvent.Error().OriginalEventBytes()
- [x] istructsmem: update byte-codec.md file
```
