### ISSUE TITLE
function to convert IRowWriter to IRowReader (3): supports all istructsmem row writers

### ISSUE THREAD

**Issue by mail2nnv** [voedger/voedger#2163]
## Problem

When trying to call `istructs.BuildRow()` with CUD event builders, we get a panic:

```
panic: unsupported operation: unknown implementation &istructsmem.recordType{rowType:istr...
```

## Decision

All `istructsmem` row writers should be supported by `istructs.BuildRow()`

```[tasklist]
### Tasks
- [x] Writer `recordType`. Reader should be cast as `istructs.IRecord`
- [x] Writer `objectType`. Reader should be cast as `istructs.IObject`
- [x] Writer `keyType`. Reader should be cast as `istructs.IKey`
- [x] Writer `valueType`. Reader should be cast as `istructs.IValue`
```
