### ISSUE TITLE
Sidecar Applications

### ISSUE THREAD

**Issue by maxim-ge** [voedger/voedger#2326]
## Internals

- [server/sidecarapps.md](https://github.com/voedger/voedger-internals/blob/main/server/sidecarapps.md)

```[tasklist]
### Tasks
- [ ] https://github.com/voedger/voedger/issues/2353
- [ ] https://github.com/voedger/voedger/issues/2369
- [ ] https://github.com/voedger/voedger/issues/2381
- [ ] https://github.com/voedger/voedger/issues/2409
- [ ] https://github.com/voedger/voedger/issues/2414
- [ ] https://github.com/voedger/voedger/issues/2420
- [ ] https://github.com/voedger/voedger/issues/2527
- [ ] https://github.com/voedger/voedger/issues/2523
- [ ] https://github.com/voedger/voedger/issues/2422
```

**Comment by host6** [comment]
```mermaid
erDiagram
	"AppProvider()" ||..|| BuiltInAppDef: returns
	BuiltInAppDef ||..}| Packages: "has field"
	BuiltInAppDef ||..|| AppDeploymentDescriptor: "has field"
	Packages ||..|| "io.FS": is
	"io.FS" ||..}| "package sql": contains
	"io.FS" ||..|| "app sql": contains
	Packages |{..|| IAppDef: "used to build"
	IAppDef ||..|| BuiltInApp: "goes to"
	AppDeploymentDescriptor ||..|| BuiltInApp: "goes to"
	BuiltInApp ||..|| BuiltInAppPackages: "goes to"
	Packages |{..|| BuiltInAppPackages: "goes to"

```
