### ISSUE TITLE
ctool: 3-node Setup

### ISSUE THREAD

**Issue by maxim-ge** [voedger/voedger#2344]
## Requirements

- 3 nodes
- Network

### Now

```mermaid
  flowchart TD

  SECluster{{SE Cluster}}:::H
  AppNode1("app-node-1"):::H
  AppNode2("app-node-2"):::H
  DBNode1("db-node-1"):::H
  DBNode2("db-node-2"):::H
  DBNode3("db-node-3"):::H

  DockerSwarm:::G
  subgraph DockerSwarm["Docker Swarm"]
    SEDockerStack:::G
    
    subgraph SEDockerStack
      voedger:::S
    end

    MonDockerStack("Monitoring Docker Stack"):::G
    subgraph MonDockerStack
      prometheus("prometheus1,2"):::S
      alertmanager("alertmanager1,2"):::S
      graphana("graphana1,2"):::S
    end

    DBDockerStack("DB Docker Stack"):::G
    subgraph DBDockerStack
      scylla("scylla1,2,3"):::S
    end
  end

  SECluster --- AppNode1
  SECluster --- AppNode2
  SECluster --- DBNode1
  SECluster --- DBNode2
  SECluster --- DBNode3

  AppNode1 --- SEDockerStack
  AppNode2 --- SEDockerStack
  AppNode1 --- MonDockerStack
  AppNode2 --- MonDockerStack

  DBNode1 --- DBDockerStack
  DBNode2 --- DBDockerStack
  DBNode3 --- DBDockerStack


  classDef G fill:#FFFFFF,stroke:#000000, stroke-width:1px, stroke-dasharray: 5 5
  classDef B fill:#FFFFB5,color:#333
  classDef S fill:#B5FFFF
  classDef H fill:#C9E7B7
```

### Want

```mermaid
  flowchart TD

  SECluster{{SE Cluster}}:::H
  DBNode1("node-1"):::H
  DBNode2("node-2"):::H
  DBNode3("node-3"):::H

  DockerSwarm:::G
  subgraph DockerSwarm["Docker Swarm"]
    SEDockerStack:::G
    
    subgraph SEDockerStack
      voedger:::S
    end

    MonDockerStack("Monitoring Docker Stack"):::G
    subgraph MonDockerStack
      prometheus("prometheus1,2"):::S
      alertmanager("alertmanager1,2"):::S
      graphana("graphana1,2"):::S
    end

    DBDockerStack("DB Docker Stack"):::G
    subgraph DBDockerStack
      scylla("scylla1,2,3"):::S
    end
  end


  SECluster --- DBNode1
  SECluster --- DBNode2
  SECluster --- DBNode3

  DBNode1 --- SEDockerStack
  DBNode1 --- DBDockerStack
  DBNode1 --- MonDockerStack

  DBNode2 --- SEDockerStack
  DBNode2 --- MonDockerStack
  DBNode2 --- DBDockerStack

  DBNode3 --- SEDockerStack
  DBNode3 --- DBDockerStack


  classDef G fill:#FFFFFF,stroke:#000000, stroke-width:1px, stroke-dasharray: 5 5
  classDef B fill:#FFFFB5,color:#333
  classDef S fill:#B5FFFF
  classDef H fill:#C9E7B7
```
```[tasklist]
### Tasks
- [ ] https://github.com/voedger/voedger/issues/2349
- [ ] https://github.com/voedger/voedger/issues/2350
- [ ] https://github.com/voedger/voedger/issues/2351
- [ ] https://github.com/voedger/voedger/issues/2412
- [ ] https://github.com/voedger/voedger/issues/2623
```

**Comment by maxim-ge** [comment]
**Keyspace upgrade**

https://docs.datastax.com/en/cql-oss/3.3/cql/cql_reference/cqlCreateKeyspace.html
