### ISSUE TITLE
devops: baseline for the fiscalcloud application

### ISSUE THREAD

**Issue by maxim-ge** [voedger/voedger#2359]
## Functional design

- fiscalcloud baseline shall be prepared together with bp3 apps baseline

## Technical design

- Build `vpm` and use `vpm baseline`

```[tasklist]
### Tasks
- [ ] https://github.com/voedger/voedger/issues/2524
- [x] bash script to check fiscalcloud backward compatibility
- [ ] https://github.com/voedger/voedger/issues/2535
```
