### ISSUE TITLE
Air: Allow all users to read CDocs in certain locations

### ISSUE THREAD

**Issue by maxim-ge** [voedger/voedger#2442]
## Motivation

- Air 688295

## Principles

- Principal user: `sys.Guest`, GuestWSID
  - If token is not specified ->` sys.Guest`
- Air role: `role.air.BOReader`
- Grant `role.air.BOReader` permissions to read `q.sys.State`
- Invite `sys.Guest` as `role.air.BOReader` to some locations
## Functional design
- owner of a location that should become a demo one calls `c.air.SwitchToDemo` with body `{}` in that location providing its token 
- after that `q.sys.State` call is allowed in that location without a token
- the rest of funcs works as before
- return a demo location back to non-demo currently is not possible
## Technical design
- `c.air.SwitchToDemo`
  - insert `sys.Subject` with `Login: sys.Login`, `Roles: air.BOReader`, `WSID: istructs.GuestWSID`
  - inserted already -> 409 conflic due of unique constraint violation on `Login` field
- grant exec on q.sys.State to role.air.BOReader
- authnz: no token provided -> emit user principal `sys.Guest` + principals by subjects by `sys.Guest` login
## Questions
- is `sys.Guest` user principal actually needed?
```[tasklist]
### Tasks
- [ ] https://github.com/voedger/voedger/issues/2454
- [ ] https://github.com/voedger/voedger/issues/2455
- [ ] https://github.com/voedger/voedger/issues/2468
- [ ] https://github.com/voedger/voedger/issues/2470
- [ ] https://github.com/voedger/voedger/issues/2472
- [ ] https://github.com/voedger/voedger/issues/2474
- [ ] https://github.com/voedger/voedger/issues/2476
```

## Context

- Air 537026
- [check](https://github.com/voedger/voedger/blob/29fb1f9d868e4b4eb253efed9513fc3ef1235ccf/pkg/registry/impl_createlogin.go#L43)
- [regexp](https://github.com/voedger/voedger/blob/29fb1f9d868e4b4eb253efed9513fc3ef1235ccf/pkg/registry/consts.go#L40)
