### ISSUE TITLE
Daily Test failed on 15/08/2024 05:14

### ISSUE THREAD

**Issue by ivvist** [voedger/voedger#2478]
https://github.com/voedger/voedger/actions/runs/10399122846
```[tasklist]
### Tasks
- [ ] https://github.com/voedger/voedger/issues/2479
- [ ] https://github.com/voedger/voedger/issues/2480
- [ ] https://github.com/voedger/voedger/issues/2483
- [ ] https://github.com/voedger/voedger/issues/2515
```

**Comment by host6** [comment]
Not happened anymore. Fixed.
