### ISSUE TITLE
Migrate to Go 1.23

### ISSUE THREAD

**Issue by maxim-ge** [voedger/voedger#2522]
## Motivation

🆒[Go 1.23 is released](https://go.dev/blog/go1.23) ([Go 1.23 Release Notes](https://tip.golang.org/doc/go1.23))
- ❓Does [slice.Backward](https://pkg.go.dev/slices@master#Backward) consume memory? 
  - Return iter from an interface (`IAppDef.QNames() iter.Seq`)
  - Use //go:noinline
- ❓https://go.dev/doc/go1.23#timer-changes
- [https://github.com/voedger/inv-go/20240822-go1_23](https://github.com/voedger/inv-go/tree/main/20240822-go1_23)

```[tasklist]
### Tasks
- [ ] https://github.com/voedger/inv-go/pull/40
- [ ] https://github.com/voedger/inv-go/issues/41
- [ ] https://github.com/voedger/voedger/issues/2652
- [ ] https://github.com/voedger/voedger/issues/2656
```

**Comment by host6** [comment]
https://github.com/voedger/inv-go/pull/40
conclusion:
- new iterators consume more memory
- async pipeline: eliminate flushTimer and just use `time.Timer.Reset(duration)`
- eliminate `coreutils.ResetTimer` just use `timer.Timer.Reset(duration)`
