### ISSUE TITLE
[epic] safe numbers conversion

### ISSUE THREAD

**Issue by host6** [voedger/voedger#2586]
### Now, in current architecture
- implicit `uint*<->int*` casting is done in many places
- json requests handling is done using `json.Unmarshal()`

### Pains 
- data loss possible on e.g. return a too big RecordID as a command result: RecordID->AsInt64()->wrong result is marshaled to json and sent to the client
- data loss is possible on casting too big `float64` to `?int*` on json unmarshaling
- data loss is possible on other values on `uint*<->int*` conversion in many palces
  - user data of type `uint32`, `uint16` etc
  - `uint64` system types like `RecordID`, `WSID` etc
    - records amount is >= 9_223_049_356_854_775_808 -> will have data loss on converting RecordID uint<->int
    - `FirstProblematicRecordBaseID = math.MaxInt64 - istructs.RecordID(istructs.ClusterAsRegisterID)*istructs.RegisterFactor+1`
    - no problems with WSID due of `istructs.NewWSID()` algorythm: no data loss even on max possible ClusterID and max possible BaseWSID. In other words can not create `istructs.WSID` using `istructs.NewWSID()` that will have data loss on converting to int64
```golang
func TestDataLossOnMaxIDs(t *testing.T) {
	id := istructs.NewRecordID(math.MaxInt64 - istructs.RecordID(istructs.ClusterAsRegisterID)*istructs.RegisterFactor + 1)
	// data loss on too big BaseRecordID
	log.Println(id)
	log.Println(int64(id))

        // same values even on max possible ClusterID and BaseWSID
	wsid = istructs.NewWSID(math.MaxUint16, math.MaxUint64)
	log.Println(wsid)
	log.Println(int64(wsid))
}  
```

### fix too big numbers in JSON
- emit number values as `json.Number` instead of float64
- istructs.IRowWriter.PutFromJSON: prevent load from numbers that are emited as float64
```golang
type istructs.JSON struct {
  Map map[string]interface{}
  dumy func() // field does nothing but makes `json.Marshal()/Unmarshal()` impossible
}
func utils.[Unmarshal|LoadFrom]JSON([]byte) (JSON, error) {
  <unmarshal to JOSN map using json.Number>
}
type IRowWriter inteface{
  PutFromJSON(istructs.JSON)
}
```
#### Approach 1 - fail when we're trying to write too big uint64 into int64 
- [istructsmem.rowType.PutNumber()](https://github.com/voedger/voedger/blob/241aaaa469a01d8f3905635822afd6e797543a60/pkg/istructsmem/types.go#L829) must check conversion safety and panic if the conversion could cause the data loss
  - also need to consider the number could be `json.Number`
-
- add panic on result>`math.MaxtInt64` in funcs:
  - `istructs.NewWSID()`
  - `istructs.NewRecordID()`
- `istructsmem.rowType.AsRecordID()` - no check requred? because we protected already against PutRecordID() of wrong int64
- command processor: 

#### Approach 2 - deny casting at all, implement methods with exact arg types
- eliminate type casting for numbers everywhere
- deny type casting for numbers by static analysis
- implement PutOffset(), PutWSID, PutRecordID, AsOffset, AsWSID, AsRecordID everywhere instead of casting int64<->uint64
  - inside these funcs - panic if uint64 value >`math.MaxInt64`, othrwise just cast to int64 and use it like now
#### Approach 3 - eliminate `uint*` types usage at all
- make all types like WSID, RecordID etc be `int*` instead of `uint*`
- seems much less problems after that, just use `json.Number` on json unmarshaling

## Related tasks
- #1366 
```[tasklist]
### Tasks
- [ ] https://github.com/voedger/voedger/issues/2559
- [ ] Types like TValue, TKeyBuilder int64->uint64? https://github.com/voedger/voedger/blob/545bb612bc48c8508b533d7e6d17776faa16ace6/pkg/state/isafestateapi/interface.go#L8
- [ ] https://github.com/voedger/voedger/issues/2657
```
