### ISSUE TITLE
[epic] appdef, parser, ...:  refactoring: get rid of USE TABLE, ACL rules per Workspace

### ISSUE THREAD

**Issue by maxim-ge** [voedger/voedger#2743]
## Requirements
 
- [x] Get rid of `USE TABLE`.
- [x] Get rid of global tables, including abstract ones.
- $VSQL_AclPerWS
  - [x] ACL rules shall be per workspace.
  - [x] AppDef: WORKSPACE owner-child relationship.
- [x] First create the `untill` workspace and make it the ancestor of the Air workspace.
- [x] parser: Make sure that embedded workspace is passed as a child workspace to appdef.
- [x] $VSQL_ExplSys: Do not use implicit sys package name except for field types (`sys.CDoc` but `int`)
- [x] $VSQL_ProjTrgByAncest: Projector may be triggered by a table from the projector workspace and from the projector workspace ancestors.

```[tasklist]
### Tasks
- [ ] https://github.com/voedger/voedger/issues/2780
- [ ] https://github.com/voedger/voedger/issues/2779
- [ ] https://github.com/voedger/voedger/issues/2745
- [ ] https://github.com/voedger/voedger/issues/2797
- [ ] https://github.com/voedger/voedger/issues/2799
- [ ] https://github.com/voedger/voedger/issues/2872
- [ ] https://github.com/voedger/voedger/issues/2971
- [ ] https://github.com/voedger/voedger/issues/2973
- [ ] https://github.com/voedger/voedger/issues/2852
```

**Comment by michael-say** [comment]
@maxim-ge what is the reason to get rid of `USE WORKSPACE`? It is used to [build workspace hierarchy](https://github.com/voedger/voedger/blob/51f44308d4c42efc157c52e1a3067bbb6395c633/pkg/parser/sql_example_app/pmain/package.vsql#L161)?
