### ISSUE TITLE
vpm

### ISSUE THREAD

**Issue by maxim-ge** [voedger/voedger#2744]
```[tasklist]
### Tasks
- [ ] https://github.com/voedger/voedger/issues/2444
- [ ] https://github.com/voedger/voedger/issues/2854
- [ ] https://github.com/voedger/voedger/issues/2817
- [ ] https://github.com/voedger/voedger/issues/2820
- [ ] https://github.com/voedger/voedger/issues/2819
- [ ] https://github.com/voedger/voedger/issues/2821
- [ ] https://github.com/voedger/voedger/issues/2850
- [ ] https://github.com/voedger/voedger/issues/2375
- [ ] https://github.com/voedger/voedger/issues/2825
- [ ] https://github.com/voedger/voedger/issues/2967
```
