### ISSUE TITLE
Describe all apps command/queries using Voedger vSQL

### ISSUE THREAD

**Issue by maxim-ge** [voedger/voedger#275]
## Motivation
All air and sys commands and queries must be desribed with vSQL

## Functional Design
For Builtin commands and queries (temp solution until AppPartitions and Engines aren;t ready):
- Take Commands and Query definitions from AppDef, the Exec-function - from resources
- Take Go-Function from Resources

## Technical Design
- commands and queries migrate example
  - move args and result declaration from Resources to sql:
  - keep the Resources declaration without args and result, keep the exec closure only
  - exception for `sys.Collection` which also declares ResultDef in IResources, see #674 
```sql
TYPE CreateLoginParams (
  Login text NOT NULL,
  AppName text NOT NULL,
  SubkectKind int32 NOT NULL,
  WSKindInitializationData text(1024) NOT NULL,
  ProfileClusterID int32 NOT NULL
);
TYPE CreateLoginUnloggedParams (
  Password text NOT NULL
);
COMMAND CreateLogin (CreateLoginParams, UNLOGGED CreateLoginUnloggedParams);
```
```go
cfg.Resources.Add(istructsmem.NewCommandFunction(
  authnz.QNameCommandCreateLogin, 
  appdef.NullQName, 
  appdef.NullQName,
  appdef.NullQName,
  execCmdCreateLogin(asp),
)
```
### Notes
- `ap.sys.SendEmailVerificationCode` is renamed to `ap.sys.ApplySendEmailVerificationCode` because there is `c.sys.SendEmailVerificationCode`
  - modified: will not send an email if the event is older than 3 days
- `q.air.UpdateSubscriptionDetailsResult` query returns void
- `q.air.CancelSubscription` has no args and returns void
- `q.air.CompleteTrialPeriod` has no args and returns void
- `q.air.ReactivateSubscription` has no args and returns void
- qnames renamed:
  - #849 
  - #672
  - `ap.sys.SendEmailVerificationCode` -> `ap.sys.ApplySendEmailVerificationCode`, now process events not older than 3 days
  - `q.sys.CDoc` -> `q.sys.GetCDoc`: QNames wil not be renamed, ok to keep both unused `sys.CDoc` QName and new `sys.GetCDoc` QName
- params and results of `q.sys.GetCDoc` and `q.sys.State` are kept in `AppConfigType` with `_local` suffix because these funcs are tested locally its own way without sql. In runtime these params and result will be replaced with ones from sql
```[tasklist]
### Tasks
- [ ] https://github.com/voedger/voedger/issues/122
- [ ] https://github.com/voedger/voedger/issues/313
- [ ] https://github.com/voedger/voedger/issues/294
- [ ] https://github.com/voedger/voedger/issues/315
- [ ] https://github.com/voedger/voedger/issues/479
- [ ] https://github.com/voedger/voedger/issues/673
- [ ] https://github.com/voedger/voedger/issues/703
- [x] https://github.com/voedger/voedger/issues/672, no pull request
- [x] adapt frontend: `c.sys.CreateLogin` -> `c.registry.CreateLogin` etc, see https://dev.untill.com/projects/#!663853
- [x] rename qnames in `dev` cluster
- [x] https://github.com/voedger/voedger/issues/672, approve the pull request
- [ ] https://github.com/voedger/voedger/issues/794
- [ ] https://github.com/voedger/voedger/issues/795
- [ ] https://github.com/voedger/voedger/issues/798
- [ ] https://github.com/voedger/voedger/issues/804
- [ ] https://github.com/voedger/voedger/issues/806
- [ ] https://github.com/voedger/voedger/issues/816
- [ ] https://github.com/voedger/voedger/issues/818
- [ ] https://github.com/voedger/voedger/issues/822
- [ ] https://github.com/voedger/voedger/issues/849
- [ ] https://github.com/voedger/voedger/issues/858
- [ ] https://github.com/voedger/voedger/issues/922
- [ ] https://github.com/voedger/voedger/issues/869
- [ ] https://github.com/voedger/voedger/issues/915
- [ ] https://github.com/voedger/voedger/issues/908
- [ ] https://github.com/voedger/voedger/issues/837
- [ ] #839
- [ ] https://github.com/voedger/voedger/issues/919
- [ ] https://github.com/voedger/voedger/issues/820
- [ ] https://github.com/voedger/voedger/issues/948
- [ ] https://github.com/voedger/voedger/issues/951
- [ ] https://github.com/voedger/voedger/issues/938
- [ ] https://github.com/voedger/voedger/issues/941
- [ ] https://github.com/voedger/voedger/issues/845
- [ ] https://github.com/voedger/voedger/issues/942
- [ ] https://github.com/voedger/voedger/issues/1039
- [ ] https://github.com/voedger/voedger/issues/1035
```
## Technical Design

```[tasklist]
### TYPE sys.Raw
- [x] https://github.com/voedger/voedger/issues/945
- [ ] https://github.com/voedger/voedger/issues/946
- [ ] https://github.com/voedger/voedger/issues/977
- [x] dev cluster: type raw: rename qname sys.JSON=> sys.Raw
- [x] https://github.com/voedger/voedger/issues/944
- [ ] https://github.com/voedger/voedger/issues/975
- [ ] https://github.com/voedger/voedger/issues/1001
- [x] https://github.com/voedger/voedger/issues/990
- [ ] https://github.com/voedger/voedger/issues/947
- [x] https://github.com/voedger/voedger/issues/989
- [x] https://github.com/voedger/voedger/issues/992
- [x] https://github.com/voedger/voedger/issues/991
```

**Comment by host6** [comment]
select c_col, value from values where p_key = 0x00110001;

**Comment by host6** [comment]
```
2023-10-28T20:46:11.736325612Z dev_airs-bp3.1.e4d3hm70iwqg@node1    | 10/28 20:46:11.735: ---: [router.(*httpService).registerHandlers.requestHandler.func8:155]: serving  POST   /api/sys/registry/140737488358554/q.registry.IssuePrincipalToken
2023-10-28T20:46:11.736476677Z dev_airs-bp3.1.e4d3hm70iwqg@node1    | 10/28 20:46:11.736: ---: [vvm.ProvideCluster.provideIBus.func6:46]: request body:
2023-10-28T20:46:11.736497948Z dev_airs-bp3.1.e4d3hm70iwqg@node1    |  {"args":{"Login":"instance6@gmail.com","Password":"123","AppName":"untill/airs-bp"},"elements":[{"fields":["PrincipalToken","WSID","WSError"]}]}
2023-10-28T20:46:11.736999222Z dev_airs-bp3.1.e4d3hm70iwqg@node1    | 10/28 20:46:11.736: ===: [istructsmem.(*appRecordsType).getRecord:374]: 9 record read: p_key = 0x001300008000000100060000000000000010 and c_col = 0x0003: value 0x01014300010000000000010003000000602c0000000000000000002200200000000000000000001c001800000000000000000000000c0000000000040022000000144d5fff8a010000144d5fff8a01000000000000080000000c0000000200000001350000060000006170705753360000
2023-10-28T20:46:11.737033256Z dev_airs-bp3.1.e4d3hm70iwqg@node1    | 10/28 20:46:11.736: ===: [istructsmem.(*rowType).setQNameID:367]: 5 requested qNameID: 323
2023-10-28T20:46:11.737042786Z dev_airs-bp3.1.e4d3hm70iwqg@node1    | 10/28 20:46:11.736: ===: [istructsmem.(*rowType).setQNameID:374]: 7 qName got: sys.WorkspaceDescriptor
2023-10-28T20:46:11.741379292Z dev_airs-bp3.1.e4d3hm70iwqg@node1    | 10/28 20:46:11.741: ===: [registry.Provide.provideIssuePrincipalTokenExec.func4:40]: 0
2023-10-28T20:46:11.741457156Z dev_airs-bp3.1.e4d3hm70iwqg@node1    | 10/28 20:46:11.741: ===: [registry.Provide.provideIssuePrincipalTokenExec.func4:66]: 1
2023-10-28T20:46:11.741779427Z dev_airs-bp3.1.e4d3hm70iwqg@node1    | 10/28 20:46:11.741: ===: [registry.GetCDocLoginID:40]: 2
2023-10-28T20:46:11.754168830Z dev_airs-bp3.1.e4d3hm70iwqg@node1    | 10/28 20:46:11.753: ===: [registry.GetCDocLoginID:46]: 3
2023-10-28T20:46:11.754497288Z dev_airs-bp3.1.e4d3hm70iwqg@node1    | 10/28 20:46:11.754: ===: [registry.GetCDocLogin:70]: 4
2023-10-28T20:46:11.762638309Z dev_airs-bp3.1.e4d3hm70iwqg@node1    | 10/28 20:46:11.762: ===: [istructsmem.(*appRecordsType).getRecord:374]: 9 record read: p_key = 0x001300008000000100060000001257af4cea and c_col = 0x0203: value 0x01012000010001257af4cea203000001081800000014002800240020001c001800140008000000040014000000240000003900020000800000000000004000000001000000800000009000000001000000250000007b22446973706c61794e616d65223a22696e7374616e63653640676d61696c2e636f6d227d0000004000000032323061396432376330353135313036323963383430653732356537623661663666313764656664376564353433616464343761333562663061386236323932000000000e000000756e74696c6c2f616972732d627000003c0000002432612430342437636770344d6f53634c4b537a50517a5136677a332e3966537a773274713345667a4f4e496372503073417133774b3144304e7853
2023-10-28T20:46:11.762685924Z dev_airs-bp3.1.e4d3hm70iwqg@node1    | 10/28 20:46:11.762: ===: [istructsmem.(*rowType).setQNameID:367]: 5 requested qNameID: 288
2023-10-28T20:46:11.762686745Z dev_airs-bp3.1.e4d3hm70iwqg@node1    | 10/28 20:46:11.762: *****: [registry.GetCDocLogin:73]: 4 type «sys.Login» not found: name not found
2023-10-28T20:46:11.762710575Z dev_airs-bp3.1.e4d3hm70iwqg@node1    | 10/28 20:46:11.762: *****: [registry.Provide.provideIssuePrincipalTokenExec.func4:69]: 1 type «sys.Login» not found: name not found
2023-10-28T20:46:11.762693414Z dev_airs-bp3.1.e4d3hm70iwqg@node1    | 10/28 20:46:11.762: ===: [istructsmem.(*rowType).setQNameID:374]: 7 qName got: sys.Login
2023-10-28T20:46:11.762817767Z dev_airs-bp3.1.e4d3hm70iwqg@node1    | 10/28 20:46:11.762: *****: [vvm.(*resultSenderErrorFirst).Close.func1:171]: type «sys.Login» not found: name not found
```

**Comment by host6** [comment]
```
[router.(*httpService).registerHandlers.requestHandler.func8:155]: serving  POST   /api/sys/registry/140737488358554/q.registry.IssuePrincipalToken
[vvm.ProvideCluster.provideIBus.func6:46]: request body:
 {"args":{"Login":"instance6@gmail.com","Password":"123","AppName":"untill/airs-bp"},"elements":[{"fields":["PrincipalToken","WSID","WSError"]}]}
===: [registry.Provide.provideIssuePrincipalTokenExec.func4:40]: 0
===: [registry.Provide.provideIssuePrincipalTokenExec.func4:66]: 1
===: [registry.GetCDocLoginID:40]: 2
===: [registry.GetCDocLoginID:46]: 3
===: [registry.GetCDocLogin:70]: 4
===: [istructsmem.(*appRecordsType).getRecord:374]: 9 record read: p_key = 0x001300008000000100060000001257af4cea and c_col = 0x0203: value 0x01012000010001257af4cea203000001081800000014002800240020001c001800140008000000040014000000240000003900020000800000000000004000000001000000800000009000000001000000250000007b22446973706c61794e616d65223a22696e7374616e63653640676d61696c2e636f6d227d0000004000000032323061396432376330353135313036323963383430653732356537623661663666313764656664376564353433616464343761333562663061386236323932000000000e000000756e74696c6c2f616972732d627000003c0000002432612430342437636770344d6f53634c4b537a50517a5136677a332e3966537a773274713345667a4f4e496372503073417133774b3144304e7853
===: [istructsmem.(*rowType).setQNameID:367]: 5 requested qNameID: 288
*****: [registry.GetCDocLogin:73]: 4 type «sys.Login» not found: name not found
*****: [registry.Provide.provideIssuePrincipalTokenExec.func4:69]: 1 type «sys.Login» not found: name not found
===: [istructsmem.(*rowType).setQNameID:374]: 7 qName got: sys.Login
*****: [vvm.(*resultSenderErrorFirst).Close.func1:171]: type «sys.Login» not found: name not found
```

**Comment by host6** [comment]
problem desc:
- rename `sys.Login` -> `registry.Login` in **untill/airs-bp** app
- remove `sys.Login` cdoc from schemas, define `registry.Login` in schemas
- make `registry`package be use by `sys/registry` app only
- current state: 
  - `untill/airsbp` app still contains `registry.Login` QName in the system view
  - `untill/airsbp` does not contain neither `cdoc.sys.Login` nor `cdoc.registry.Login` singletons
  - `sys/registry` app has `sys.Login` QName in the system view
  - `sys/registry` app is the single app that contains `registry` package included 
  - `sys/registry` app has `registry.Login` QName in the system view because it added new in `registry` package
  - `sys/registry`app dos not contain `cdoc.sys.Login` singleton because it removed from the `sys` package 
- `cdoc.registry.Login` singleton is queried by its ID in `sys/registry` app during `q.sys.IssuePrincipalToken` execution
  - the entire record is read
  - QNameID of the record is got to determine the actual QName - 288 (0x0120)
  - `sys.Login` QName is got from the system view by ID 288 
  - `IType` is queried for this QName `sys.Login`- it is failed because `cdoc.sys.Login` signleton definition is removed from the schema of `sys/registry` app (there is just new `cdoc.registry.Login`singleton only
