### ISSUE TITLE
[epic] Nullability

### ISSUE THREAD

**Issue by maxim-ge** [voedger/voedger#2772]
## Context

- [istructs.ICUDRow.ModifiedFields](https://github.com/maxim-ge/voedger/blob/62dee433177fffd2a07428a13027a1ead6a2ae21/pkg/istructsmem/tables-types.go#L59)

## Principles

- Event: CUDs: old values are NOT stored, list of emptied fields (indexes) ARE stored.
- request json, null value -> ignored 
- json, empty string value
  - Record, View
    - dynobuffer: field is not stored
    - istructs: empty string is returned
  - Event: ModifiedFields(func(appdef.FieldName, newValue interface{}) bool)
    - newValue: empty string
- json, empty object value (`{}`)
  - Record, View
    - dynobuffer: object is not stored
    - istructs: IRowReader with zero-valued fields
  - Event: ModifiedFields(func(appdef.FieldName, newValue interface{}) bool)
    - newValue: empty Reader

```[tasklist]
### Tasks
- [ ] https://github.com/voedger/voedger/issues/2773
- [ ] https://github.com/voedger/voedger/issues/2783
- [ ] https://github.com/voedger/voedger/issues/2784
- [ ] https://github.com/voedger/voedger/issues/2814
- [ ] https://github.com/voedger/voedger/issues/2785
```
