### ISSUE TITLE
ctool: Monitoring (+routing)

### ISSUE THREAD

**Issue by maxim-ge** [voedger/voedger#278]
```[tasklist]
### Tasks
- [ ] https://github.com/voedger/voedger/issues/787
- [x] https://github.com/voedger/voedger/issues/874
- [ ] https://github.com/voedger/voedger/issues/339
- [ ] https://github.com/voedger/voedger/issues/740
- [ ] https://github.com/voedger/voedger/issues/1192
```
