### ISSUE TITLE
parser, appdef: Tags

### ISSUE THREAD

**Issue by maxim-ge** [voedger/voedger#2889]
## Requirements
 
- Parser shall not "expand" expressions with tags, expression with tags shall be handled by appdef.
- Tags cannot be declared on package-level, only within the workspace
- Tags can not be used in derived workspaces
- $VSQL_TagNonExp
  - [x] Do not export tags. Tag is a non-exported (can not be used from other packages) package-level identifier (e.g. a table in the same package can not have the same name) that is scoped per workspace (being declared in one workspace it can NOT be used in another, incliding descendants). 

```[tasklist]
### Tasks
- [ ] #2792
- [ ] https://github.com/voedger/voedger/issues/2893
- [ ] https://github.com/voedger/voedger/issues/2894
```
