### ISSUE TITLE
Optimize memory allocations, PLog, WLog spot read

### ISSUE THREAD

**Issue by maxim-ge** [voedger/voedger#345]
## Problem

- [Large space memory allocation at ReadPLog implementation](https://github.com/voedger/voedger/blob/810f465de1cf64d8596d1ad5b58f16abd474c3f2/pkg/istructsmem/impl.go#L295:L298)
- Obrained using
go tool pprof -http :8088 -focus 'fastcache.\(\*bucket\).Get' cpu0701
- See also go tool pprof -http :8088 -focus 'istructsmem\.\(\*rowType\)\.clear' cpu0701

## Technical Design

- IPlogEvent.Release(), IWLogEvent.Release()
- sync.Pool
- Maximum size for reuse is limited by 64K
```[tasklist]
### Tasks
- [ ] istructs: comments: It's desirable but not necessary to call Release() (ReadPLog(), ReadWLog())
- [ ] istructsmem: implement pool and Release() methods
- [ ] projectors: Release events
```
