### ISSUE TITLE
Describe all apps view/projectors using vSQL

### ISSUE THREAD

**Issue by michael-say** [voedger/voedger#376]
## Principles
- Projectors are BUILTIN or WASM extensions
- Projectors can be declared as syncronous or asyncronous (default)
- Views are generated by projectors. A view can only be generated by not more than one projector

### Projectors
- Projector definition contains:
  - the name of projector
  - the list of storages it reads the state from
  - the list of storages it generates the intents for
- [Example syntax](https://github.com/voedger/voedger/blob/6dfdc092731829b0705a18aabe602c3e1b5570d7/pkg/parser/sql_example_app/pmain/package.sql#L189C8-L189C9)

### Views
- View definition contains:
  - the name of view
  - the list of fields
  - the structure of keys
  - the way this view is generated (by custom projector, automatically with "select" clause)

### Stoages
- STORAGEs are defined in [sys package](https://github.com/voedger/voedger/blob/6dfdc092731829b0705a18aabe602c3e1b5570d7/pkg/parser/sql_example_syspkg/system.sql#L35),  MVP doesn't allow to register user-defined storages
 
## Technical Design
- (done) Semantic analysis prevents storages to be used by projectors in an non-allowed way
- Semantic analysis must check that a projector, responsible for generation of a view, declares this view in INTENTS section
- AppDef doesn't contain the Storage definitions (MVP). Storages are hardcoded, even if they're declared in `sys` package
- The names of STORAGEs in parser are hardcoded to prevent registering user-defined storages. 
- The ExtensionEngine verifies storage keys when Projector requests data from State, or generates Intents for.
- Projector reads event from storage `sys.Args` by the name `Event`
- `view.sys.NextWSID` will not be defined in sql because it is the result of a command, not projector. That is not supported in sql.
- `p.sys.ViewSubjectIdx` -> `p.sys.ApplyViewSubjectIdx`

## See Also
- [AST projector syntax](https://github.com/voedger/voedger/blob/6dfdc092731829b0705a18aabe602c3e1b5570d7/pkg/parser/types.go#L374C28-L374C28)

```[tasklist]
### Tasks
- [ ] https://github.com/voedger/voedger/issues/377
- [ ] https://github.com/voedger/voedger/issues/405
- [ ] https://github.com/voedger/voedger/issues/407
- [ ] https://github.com/voedger/voedger/issues/595
- [ ] https://github.com/voedger/voedger/issues/612
- [ ] https://github.com/voedger/voedger/issues/616
- [ ] https://github.com/voedger/voedger/issues/622
- [ ] https://github.com/voedger/voedger/issues/432
- [ ] https://github.com/voedger/voedger/issues/743
- [ ] https://github.com/voedger/voedger/issues/744
- [ ] https://github.com/voedger/voedger/issues/752
- [ ] https://github.com/voedger/voedger/issues/861
- [ ] https://github.com/voedger/voedger/issues/897
- [ ] https://github.com/voedger/voedger/issues/746
- [ ] https://github.com/voedger/voedger/issues/923
- [ ] https://github.com/voedger/voedger/issues/954
- [ ] https://github.com/voedger/voedger/issues/397
- [ ] https://github.com/voedger/voedger/issues/876
- [ ] https://github.com/voedger/voedger/issues/972
- [x] https://github.com/voedger/voedger/issues/993
- [x] https://github.com/voedger/voedger/issues/994
- [ ] https://github.com/voedger/voedger/issues/1019
- [ ] https://github.com/voedger/voedger/issues/1021
- [ ] https://github.com/voedger/voedger/issues/875
- [ ] https://github.com/voedger/voedger/issues/1025
- [ ] https://github.com/voedger/voedger/issues/1023
- [ ] https://github.com/voedger/voedger/issues/1024
- [ ] https://github.com/voedger/voedger/issues/1050
- [ ] https://github.com/voedger/voedger/issues/1048
- [ ] https://github.com/voedger/voedger/issues/1084
- [ ] https://github.com/voedger/voedger/issues/1058
- [ ] https://github.com/voedger/voedger/issues/1092
```

```[tasklist]
### Tasks
```
