### ISSUE TITLE
ACL Rules

### ISSUE THREAD

**Issue by michael-say** [voedger/voedger#394]
## Motivation

- Use ACL from VSQL, currently it is hardcoded ([pkg/iauthnzimpl/impl_acl.go](https://github.com/voedger/voedger/blob/main/pkg/iauthnzimpl/impl_acl.go))

## Design

- [internals/server/vsql/aclrules](https://github.com/voedger/voedger-internals/blob/main/server/vsql/aclrules.md#L20-L24)

## Context

- [Current grants](https://github.com/voedger/voedger/blob/939a6ec0c5acb1061f49a41258cda24aff6d3c2b/pkg/iauthnzimpl/impl_acl.go#L34) 
- [IsAllowed(appart...)](https://github.com/voedger/voedger/blob/685c869c8bf2b0f219d99015460848db52ca6b69/pkg/iauthnzimpl/impl_acl.go#L16)
- [Design concepts](https://github.com/voedger/voedger/tree/main/design/authnz)
- [vsql example](https://github.com/voedger/voedger/blob/685c869c8bf2b0f219d99015460848db52ca6b69/pkg/parser/sql_example_app/pmain/package.vsql#L280)
- [pkg/acl](https://github.com/voedger/voedger/blob/main/pkg/acl/interface.go)
- [pkg/iauthnzimpl/impl.go](https://github.com/voedger/voedger/blob/main/pkg/iauthnzimpl/impl.go)
- [pkg/iauthnzimpl/impl_acl.go](https://github.com/voedger/voedger/blob/main/pkg/iauthnzimpl/impl_acl.go)

## ??? Unclear

See #928
```sql
REVOKE INHERITED
```

```[tasklist]
### Tasks
- [ ] https://github.com/voedger/voedger/issues/2473
- [ ] https://github.com/voedger/voedger/issues/864
- [x] https://github.com/voedger/voedger/issues/949
- [ ] https://github.com/voedger/voedger/issues/395
- [ ] https://github.com/voedger/voedger/issues/396
- [ ] https://github.com/voedger/voedger/issues/1955
- [ ] https://github.com/voedger/voedger/issues/1961
- [ ] https://github.com/voedger/voedger/issues/2516
- [ ] ———————————
- [ ] https://github.com/voedger/voedger/issues/2509
- [ ] https://github.com/voedger/voedger/issues/2521
- [ ] https://github.com/voedger/voedger/issues/2561
- [ ] #2724
- [ ] https://github.com/voedger/voedger/issues/2695
- [ ] https://github.com/voedger/voedger/issues/2696
- [ ] https://github.com/voedger/voedger/issues/2725
- [ ] https://github.com/voedger/voedger/issues/2726
- [ ] https://github.com/voedger/voedger/issues/2718
- [ ] https://github.com/voedger/voedger/issues/2826
- [ ] https://github.com/voedger/voedger/issues/2747
- [ ] https://github.com/voedger/voedger/issues/2748
- [ ] https://github.com/voedger/voedger/issues/2933
- [ ] https://github.com/voedger/voedger/issues/2692
- [ ] https://github.com/voedger/voedger/issues/2954
- [ ] https://github.com/voedger/voedger/issues/3011
- [ ] https://github.com/voedger/voedger/issues/3018
- [ ] https://github.com/voedger/voedger/issues/2997
- [ ] https://github.com/voedger/voedger/issues/3113
- [x] drop pkg/iauthnz, impl_acl.go
- [x] processors: eliminate temporary suppressing `role not found` error (#3011)
- [x] return back SELECT rule checking (#3018)
- [ ] https://github.com/voedger/voedger/issues/3126
- [ ] https://github.com/voedger/voedger/issues/3130
- [ ] https://github.com/voedger/voedger/issues/3148
- [ ] https://github.com/voedger/voedger/issues/3129
- [ ] https://github.com/voedger/voedger/issues/3127
```

**Comment by host6** [comment]
@maxim-ge, describe how SELECT permissions should work:
- `grant execute on q.sys.Collection` + `revoke select on Table1` -> could any field of the `Table1` be selected?
- are we need permission control on Field level? e.g. `grant execute on q.sys.Collection` + `revoke select on Table1.Field1` - select of Table1.Field1 denied?
