### ISSUE TITLE
performance: Optimize top allocators (12.7.23)

### ISSUE THREAD

**Issue by maxim-ge** [voedger/voedger#400]
## Motivation

https://github.com/untillpro/air-perftests/blob/main/202307111900/profiles/top-heap-objects.txt
![image](https://github.com/voedger/voedger/assets/11589750/9ed61450-3727-4829-ad92-a58fdd6cb15c)

### flatbuffers/go.(*Builder).growByteBuffer

<details><summary>Details</summary>
<p>

![image](https://github.com/voedger/voedger/assets/11589750/1d980a26-a6ff-44e0-87b8-a50fef0dc860)

</p>
</details> 

- ~Do not use dyno in key bulders~
- Optimize use dyno in key bulders

### istructsmem.loadElement
<details><summary>Details</summary>
<p>

![image](https://github.com/voedger/voedger/assets/11589750/fd2a54f9-b281-4343-b9a0-8d2456539c59)

</p>
</details> 

### dynobuffers.(*Buffer).set

<details><summary>Details</summary>
<p>

![profile](https://github.com/voedger/voedger/assets/11589750/3ee5bb8a-775f-4fd9-9a32-c2d65f1fdfd3)

</p>
</details> 

- Will be somehow reduced by ~"Do not use dyno in key bulders"~ "Optimize use dyno in key bulders"
- slice of values instead of pointers?
![image](https://github.com/voedger/voedger/assets/11589750/52062f89-ab23-4697-b978-f666535722e7)

### flatbuffers/go.NewBuilder (inline)

<details><summary>Details</summary>
<p>

![cpu-builder](https://github.com/voedger/voedger/assets/11589750/36110163-b293-4ebf-a053-164d25588b79)

</p>
</details> 

- Will be somehow reduced by ~"Do not use dyno in key bulders"~ "Optimize use dyno in key builders"

```[tasklist]
### Tasks
- [ ] https://github.com/voedger/voedger/issues/413
- [ ] https://github.com/voedger/voedger/issues/411
- [ ] https://github.com/voedger/voedger/issues/426
- [ ] https://github.com/voedger/voedger/issues/428
- [ ] https://github.com/voedger/voedger/issues/433
- [ ] https://github.com/voedger/voedger/issues/455
```
