### ISSUE TITLE
Describe Air Workspaces using vSQL

### ISSUE THREAD

**Issue by michael-say** [voedger/voedger#404]
```[tasklist]
### Tasks
- [ ] https://github.com/voedger/voedger/issues/403
- [ ] https://github.com/voedger/voedger/issues/456
- [ ] https://github.com/voedger/voedger/issues/466
- [ ] https://github.com/voedger/voedger/issues/467
- [ ] https://github.com/voedger/voedger/issues/550
- [ ] https://github.com/voedger/voedger/issues/734
- [ ] https://github.com/voedger/voedger/issues/733
- [ ] https://github.com/voedger/voedger/issues/468
- [ ] https://github.com/voedger/voedger/issues/627
- [ ] https://github.com/voedger/voedger/issues/1228
- [ ] https://github.com/voedger/voedger/issues/1246
- [ ] https://github.com/voedger/voedger/issues/1303
- [ ] https://github.com/voedger/voedger/issues/1299
- [ ] https://github.com/voedger/voedger/issues/1298
- [ ] https://github.com/voedger/voedger/issues/1389
- [ ] https://github.com/voedger/voedger/issues/1411
- [ ] https://github.com/voedger/voedger/issues/1439
- [ ] https://github.com/voedger/voedger/issues/1551
- [ ] https://github.com/voedger/voedger/issues/1311
- [ ] https://github.com/voedger/voedger/issues/1433
- [ ] https://github.com/voedger/voedger/issues/1451
- [ ] https://github.com/voedger/voedger/issues/1499
- [x] bp3: devide `ap.air.ApplyUPTransferEvent` with 2 parts (https://dev.untill.com/projects/#!681932)
- [ ] https://github.com/voedger/voedger/issues/1563
- [ ] https://github.com/voedger/voedger/issues/1460
- [ ] https://github.com/voedger/voedger/issues/1430
- [ ] https://github.com/voedger/voedger/issues/1581
- [ ] https://github.com/voedger/voedger/issues/1590
- [ ] https://github.com/voedger/voedger/issues/1592
- [ ] frontend: call funcs in theirs workspaces only (https://dev.untill.com/projects/#!680347)
- [ ] https://github.com/voedger/voedger/issues/1623
- [ ] https://github.com/voedger/voedger/issues/1624
- [ ] https://github.com/voedger/voedger/issues/1643
- [ ] https://github.com/voedger/voedger/issues/1587
- [ ] https://github.com/voedger/voedger/issues/1622
- [ ] https://github.com/voedger/voedger/issues/1374
- [ ] https://github.com/voedger/voedger/issues/1787
```

```[tasklist]
### Errors on taking QNames from Workspaces
- [ ] https://github.com/voedger/voedger/issues/1637
- [ ] https://github.com/voedger/voedger/issues/1639
- [ ] https://github.com/voedger/voedger/issues/1640
- [ ] https://github.com/voedger/voedger/issues/1656
- [ ] https://github.com/voedger/voedger/issues/1658
- [ ] https://github.com/voedger/voedger/issues/1673
- [ ] https://github.com/voedger/voedger/issues/1678
- [ ] https://github.com/voedger/voedger/issues/1683
- [ ] https://github.com/voedger/voedger/issues/1686
```
