### ISSUE TITLE
DevOps

### ISSUE THREAD

**Issue by maxim-ge** [voedger/voedger#459]
```[tasklist]
### Tasks
- [ ] Do not run the Daily Test Suite on forks
```

**Comment by host6** [comment]
see also: https://github.com/untillpro/qs/issues/21

**Comment by maxim-ge** [comment]
```[tasklist]
### Tasks
- [ ] https://github.com/voedger/voedger/issues/460
- [ ] https://github.com/voedger/voedger/issues/498
- [ ] https://github.com/voedger/voedger/issues/514
- [ ] https://github.com/voedger/voedger/issues/543
- [x] qs dev: -d should pull upstream main
- [ ] https://github.com/voedger/voedger/issues/645
- [ ] https://github.com/voedger/voedger/issues/669
- [x] https://github.com/voedger/voedger/issues/684
- [ ] https://github.com/voedger/voedger/issues/683
- [ ] https://github.com/voedger/voedger/issues/685
```

**Comment by maxim-ge** [comment]
Migrated to https://github.com/orgs/voedger/projects/11/views/17
