### ISSUE TITLE
SQL syntax improvements

### ISSUE THREAD

**Issue by michael-say** [voedger/voedger#464]
```[tasklist]
### Tasks
- [ ] https://github.com/voedger/voedger/issues/465
- [ ] https://github.com/voedger/voedger/issues/483
- [ ] https://github.com/voedger/voedger/issues/484
- [ ] https://github.com/voedger/voedger/issues/485
- [ ] https://github.com/voedger/voedger/issues/489
- [ ] https://github.com/voedger/voedger/issues/499
- [ ] https://github.com/voedger/voedger/issues/488
- [ ] https://github.com/voedger/voedger/issues/519
- [ ] https://github.com/voedger/voedger/issues/552
- [ ] https://github.com/voedger/voedger/issues/554
```
