### ISSUE TITLE
Air as a Voedger application

### ISSUE THREAD

**Issue by maxim-ge** [voedger/voedger#47]
## Context

- Project [Air as a Voedger application](https://github.com/orgs/voedger/projects/8?pane=info)
- dev.heeus.io/launchpad: [Draft SQL schema parser](https://dev.heeus.io/launchpad/#!26744)

## Tasks

```[tasklist]
### Product
- [ ] https://github.com/voedger/voedger/issues/272
- [ ] #167
- [ ] https://github.com/voedger/voedger/issues/464
- [ ] https://github.com/voedger/voedger/issues/643
- [ ] https://github.com/voedger/voedger/issues/639
- [ ] https://github.com/voedger/voedger/issues/644
- [ ] https://github.com/voedger/voedger/issues/658
- [ ] https://github.com/voedger/voedger/issues/675
```

```[tasklist]
### Technical
- [ ] https://github.com/voedger/voedger/issues/636
- [ ] https://github.com/voedger/voedger/issues/662
- [ ] https://github.com/voedger/voedger/issues/701
- [ ] https://github.com/voedger/voedger/issues/704
- [ ] https://github.com/voedger/voedger/issues/663
```

```[tasklist]
### Technical (done)
- [x] https://github.com/voedger/voedger/issues/547
- [ ] https://github.com/voedger/voedger/issues/534
- [ ] https://github.com/voedger/voedger/issues/584
- [ ] https://github.com/voedger/voedger/issues/586
- [ ] https://github.com/voedger/voedger/issues/568
- [ ] #41
- [ ] https://github.com/voedger/voedger/issues/641
- [ ] #42
- [ ] #36
- [ ] #38
- [ ] #48
- [ ] #57
- [ ] #56
- [ ] #59
- [ ] #77
- [ ] #96
- [ ] untillpro/airs-bp3#455
- [ ] #103
- [ ] #124
- [ ] #166
- [ ] #221
- [ ] #214
- [ ] https://github.com/voedger/voedger/issues/385
```

**Comment by maxim-ge** [comment]
Migrated to https://github.com/orgs/voedger/projects/11/views/12
