### ISSUE TITLE
Deactivate Workspace

### ISSUE THREAD

**Issue by maxim-ge** [voedger/voedger#53]
## Problem/Motivation/Requirements

- air: [Delete Resellers and Payments Locations](https://dev.untill.com/projects/#!635060)
- As as Developer I created a lot of test child workspaces and now I do not want to see them anymore

## Design

[deactivate-workspace.md](https://github.com/voedger/voedger/blob/main/design/workspaces/deactivate-workspace.md)

```[tasklist]
## TODO
- [x] #85
- [x] WorkspaceID - WSID must be a separate field
- [x] sys.Subject: WSID: NOT NULL
- [x] #148
- [x] `view.sys.WorkspaceIDIdx` keeps a list of workspaces
- [x] Skip deactivating `cdoc.sys.WorkspaceID` if it is missing because now these docs will be located in a different workspace according to #85
- [x] update doc: deactivate owner doc, set `cdoc.sys.WorkspaceDescriptor.Status = Inactive`
```

**Comment by host6** [comment]
и профили пользователей всегда хранятся в main cluster получается?
надо TargetClusterID передавать в c.sys.CreateWorkspaceID, а то теперь он в main cluster вызывается и использует его при GetNextWSID()
