### ISSUE TITLE
bp3, voedger: Guarantee schemas backward compatibility

### ISSUE THREAD

**Issue by maxim-ge** [voedger/voedger#646]
## Motivation

Changes in app schemas should be backward compatible

## Principles
- Temporary solution: bp3 is used to export baseline sql scripts and to check compatibility between current and the exported scripts
- When app schema changed by developers, the backward compatibility is checked automatically
- Exception: In case of known incompatibility (eg we sure that there is no data yet) it is fixed manually 

## Terms

- `Baseline Schemas` - version of the app schemas, to compare current schemas compatibility with. Placed in the folder `airsbp3/baseline_schemas`
  - [Baseline Schemas](https://github.com/voedger/voedger/blob/29baba807aca3535910c575141a3e9854ba4fed2/pkg/parser/example_exported_apps)
  - [apps.yaml](https://github.com/voedger/voedger/blob/29baba807aca3535910c575141a3e9854ba4fed2/pkg/parser/example_exported_apps/apps.yaml)
### Configuration

- Devops runs `bp3 baseline_schemas <baseline schemas folder>` to export current app schemas to `Baseline Schemas` and commits to main 
  - https://github.com/untillpro/airs-bp3/tree/rc

### Commit to main branch

- Some unit test checks compatibility of the current scripts with `Baseline Schemas`

### Ignore error

-  Developer adds ignore lines to the apps.yaml

### Update  Baseline Schemas (on Issue RC)

- Update Baseline Schemas in main branch
- Commit new Baseline Schemas to main branch
- Issue RC

### `Baseline Schemas`: bp3 baseline_schemas <baseline schemas folder>

- <baseline schemas folder> must be completely cleaned up!!!
- Lists all vSQL packages and exports them as folders to "pkg" subfolder (including `sys`)
- Lists all vSQL applications and exports their packages to `apps.yaml`
   

## TODO

```[tasklist]
### Tasks
- [ ] https://github.com/voedger/voedger/issues/617
- [ ] https://github.com/voedger/voedger/issues/736
- [ ] https://github.com/voedger/voedger/issues/775
- [ ] https://github.com/voedger/voedger/issues/778
- [ ] https://github.com/voedger/voedger/issues/783
- [ ] https://github.com/voedger/voedger/issues/825
- [ ] https://github.com/voedger/voedger/issues/827
- [ ] https://github.com/voedger/voedger/issues/777
- [ ] https://github.com/voedger/voedger/issues/830
- [ ] https://github.com/voedger/voedger/issues/799
- [ ] https://github.com/voedger/voedger/issues/800
- [ ] https://github.com/voedger/voedger/issues/835
- [ ] https://github.com/voedger/voedger/issues/838
- [ ] https://github.com/voedger/voedger/issues/851
- [ ] https://github.com/voedger/voedger/issues/854
- [ ] https://github.com/voedger/voedger/issues/855
- [ ] https://github.com/voedger/voedger/issues/844
- [x] devops: Update Baseline Schemas (on Issue RC) (https://dev.untill.com/projects/#!670064)
```

**Comment by maxim-ge** [comment]
@michael-say I do not understand how can we check bp3 app...

**Comment by maxim-ge** [comment]
Historical:

- `bp3 schemas testcompat <folder>` - checks compatibility of schemas to schemas exported in the specified folder. 
  - [load ASTs](#775) of exported applications and build appdefs [example](https://github.com/voedger/voedger/blob/cb4c44439e9f7ea18ce2474f79029f97000b40d8/pkg/parser/impl_test.go#L1632)
  - [compare](https://github.com/voedger/voedger/blob/main/pkg/appdefcompat/README.md) current appdef to the exported appdef

**Comment by host6** [comment]
need to run a projetor async, then sync, e.g. #663, - should it be considered on schemas compare?
