### ISSUE TITLE
Validation

### ISSUE THREAD

**Issue by host6** [voedger/voedger#650]
## Problem

-  Some validations are duplicated (processor and istructsmem): Referential integrity

## Principles

- Well formed: json parsing + istructs.EventBuilder
  - The only exception: ICUD.Update(record IRecord) IRowWriter (tech dept)
- Validation: CommandProcessor
  - Checks
  - Custom validation
- Is a part of the Core
  - Only Air checks uses deprecated istructs.AppConfitType.CUDValidators, EventValidators  (tech dept)

## Functional Design

-

## Technical Design

- RawEvent in "sys.Args" storage

- Problem (hot): no validation is allowed after write to PLog according to https://dev.heeus.io/launchpad/#!24631

**Describe the solution you'd like**
- validation point
  - implement a separate validator func in `istructsmem` that could be called by Command Processor right before write to PLog?
  - implement all validations on `IEvents.PutPLog()` ?
- validation failed -> `sys.Error` event should be written to PLog on `IEvents.PutPlog()`
  - no `sys.Error` events in WLog
  - consider neither `IRecords.Apply()` nor write to WLog will not be done
- implement a tool to check key existance in the storage? Otherwise we need to read the entire record to check if the ref target exists
  - bad idea: key exists -> need to read `QNameID` anyway
- consider that nullable ref field could have `NullRecordID` (zero) value. That means "unlink"
### Related tasks
- https://github.com/voedger/voedger/issues/20
- https://github.com/voedger/voedger/issues/172
```[tasklist]
### Tasks
- [ ] https://github.com/voedger/voedger/issues/722
- [ ] https://github.com/voedger/voedger/issues/663
- [ ] https://github.com/voedger/voedger/issues/177
- [ ] https://github.com/voedger/voedger/issues/958
- [ ] move ref integrity checking from the validator to the core
- [ ] One record per CUD
- [ ] References: Validate CUD => ODoc in argument reference
- [ ] Raw ID validation (e.g. it must be unique)
```
