### ISSUE TITLE
Migrate to IAppPartitions

### ISSUE THREAD

**Issue by maxim-ge** [voedger/voedger#656]
## Requirements

- For all apps: blobber, registry, router, bp3
  - Use appparts instead of istructs  
  - Configure built-in AppPartitions before wiring

## Design
-  [VVM: Execute assigned AppPartition](https://github.com/voedger/voedger/tree/main/design#vvm-execute-assigned-apppartition)
- [async actualizers](https://github.com/voedger/voedger/tree/main/design/0-inv/20240306-async)

```[tasklist]
### Tasks
- [ ] https://github.com/voedger/voedger/issues/1681
- [ ] https://github.com/voedger/voedger/issues/1416
- [ ] https://github.com/voedger/voedger/issues/2141
- [ ] https://github.com/voedger/voedger/issues/2194
- [ ] https://github.com/voedger/voedger/issues/1464
- [x] async actualizers: eliminate endless free app parts awaiting
- [x] bp3: Use appparts instead of istructs.IAppStructs (Borrow(), AppStructs(), Release()...)
- [x] https://github.com/voedger/voedger/issues/1351 (deleted)
- [x] istructs: cleanup: AsyncProjectors(), SyncProjectors()
- [x] voedger: commands
- [x] bp3: commands
```

```[tasklist]
### Projectors shall be accessible through ExtEngineKind\_BuiltIn
- [ ] https://github.com/voedger/voedger/issues/1688
- [ ] https://github.com/voedger/voedger/issues/1692
- [ ] https://github.com/voedger/voedger/issues/1617
- [ ] https://github.com/voedger/voedger/issues/1710
- [ ] https://github.com/voedger/voedger/issues/1689
- [ ] https://github.com/voedger/voedger/issues/1779
- [ ] https://github.com/voedger/voedger/issues/1780
- [ ] https://github.com/voedger/voedger/issues/1797
- [ ] https://github.com/voedger/voedger/issues/1806
- [ ] https://github.com/voedger/voedger/issues/1781
```

**Comment by mail2nnv** [comment]
Extra fix
