### ISSUE TITLE
A&D: Migrate to IAppPartitions

### ISSUE THREAD

**Issue by maxim-ge** [voedger/voedger#661]
## Context

- [IAppPartitions Design](https://github.com/voedger/voedger/tree/main/design#vvm-execute-assigned-apppartition)
- [VVM Design](https://github.com/voedger/voedger/tree/main/design/vvm)

## Analysis

- apparts
  - IAppPartitions.AddApp(), IAppPartitions.AddOrReplaceAppPartition(app AppQName, appdef, pools)
- apppartsctl
  - Like https://github.com/voedger/voedger/tree/main/pkg/ihttpctl

```[tasklist]
### Tasks
- [ ] appparts, apppartsctl: interfaces
- [ ] Implement appparts (with extensions)
- [ ] Implement apppartsctl
- [ ] Use appparts instead of iappstructs
```
