### ISSUE TITLE
record ID leads to different table

### ISSUE THREAD

**Issue by host6** [voedger/voedger#688]
**Describe the bug**
update a record, provide new fields values, server replies with an error that says he expecting fields from the another table. I.e. client provides a record ID to update but server sees that this record ID leads to the another table

```
08:59:31.521: ---: [vvm.provideIBus.func1:46]: request body:
2023-09-27T08:59:31.522098428Z dev_airs-bp3.1.i80dhuud5hzd@node1    |  {"cuds":[{"sys.ID":322685000131394,"fields":{"sys.IsActive":true,"name":"Burger menu","article_number":0,"must_combined":0,"id_departament":322685000131131,"id_courses":0,"pc_color":0,"id_free_option":0}},{"sys.ID":322685000131413,"fields":{"sys.IsActive":true,"id_preparation_area":322685000131180,"purpose":0}},{"sys.ID":322690000000000,"fields":{"sys.IsActive":true,"id_sales_area":322690000000016,"id_articles":322685000131394}},{"sys.ID":322685000131397,"fields":{"sys.IsActive":true,"id_sales_area":322685000131078,"id_articles":322685000131394}},{"sys.ID":322685000131396,"fields":{"sys.IsActive":true,"id_sales_area":322685000131087,"id_articles":322685000131394}},{"sys.ID":322685000131395,"fields":{"sys.IsActive":true,"id_sales_area":322685000131098,"id_articles":322685000131394}},{"sys.ID":322685000131404,"fields":{"sys.IsActive":false,"free_of_charge":false,"option_number":0,"sequence":0,"sm_sequence":0,"lg_sequence":0,"option_type":0,"max_quantity":0,"compose":0,"id_options":322685000131405,"id_courses":322685000131111}},{"sys.ID":322685000131405,"fields":{"sys.IsActive":true,"name":"Drink","option_type":80,"opt_number":0}},{"sys.ID":322685000131410,"fields":{"sys.IsActive":true,"option_number":0,"sequence":0,"sm_sequence":0,"lg_sequence":0,"option_type":0,"id_articles":322685000131191,"option_print":0,"option_text":"","option_manual":0,"show_in_ks":0}},{"sys.ID":322685000131411,"fields":{"sys.IsActive":true,"id_prices":322685000131077,"price":10000,"id_currency":322685000131072,"vat":0,"vat_sign":"","use_group_vat":0}},{"sys.ID":322685000131408,"fields":{"sys.IsActive":true,"option_number":0,"sequence":0,"sm_sequence":0,"lg_sequence":0,"option_type":0,"id_articles":322685000131196,"option_print":0,"option_text":"","option_manual":0,"show_in_ks":0}},{"sys.ID":322685000131409,"fields":{"sys.IsActive":true,"id_prices":322685000131077,"price":11000,"id_currency":322685000131072,"vat":0,"vat_sign":"","use_group_vat":0}},{"sys.ID":322685000131406,"fields":{"sys.IsActive":true,"option_number":0,"sequence":0,"sm_sequence":0,"lg_sequence":0,"option_type":0,"id_articles":322685000131201,"option_print":0,"option_text":"","option_manual":0,"show_in_ks":0}},{"sys.ID":322685000131407,"fields":{"sys.IsActive":true,"id_prices":322685000131077,"price":12000,"id_currency":322685000131072,"vat":0,"vat_sign":"","use_group_vat":0}},{"sys.ID":322685000131398,"fields":{"sys.IsActive":false,"free_of_charge":false,"option_number":0,"sequence":0,"sm_sequence":0,"lg_sequence":0,"option_type":0,"max_quantity":0,"compose":0,"id_options":322685000131399,"id_courses":322685000131111}},{"sys.ID":322685000131399,"fields":{"sys.IsActive":true,"name":"Burger","option_type":80,"opt_number":0}},{"sys.ID":322685000131402,"fields":{"sys.IsActive":true,"option_number":0,"sequence":0,"sm_sequence":0,"lg_sequence":0,"option_type":0,"id_articles":322685000131226,"option_print":0,"option_text":"","option_manual":0,"show_in_ks":0}},{"sys.ID":322685000131403,"fields":{"sys.IsActive":true,"id_prices":322685000131077,"price":20000,"id_currency":322685000131072,"vat":0,"vat_sign":"","use_group_vat":0}},{"sys.ID":322685000131400,"fields":{"sys.IsActive":true,"option_number":0,"sequence":0,"sm_sequence":0,"lg_sequence":0,"option_type":0,"id_articles":322685000131231,"option_print":0,"option_text":"","option_manual":0,"show_in_ks":0}},{"sys.ID":322685000131401,"fields":{"sys.IsActive":true,"id_prices":322685000131077,"price":30000,"id_currency":322685000131072,"vat":0,"vat_sign":"","use_group_vat":0}}]}
2023-09-27T08:59:31.523221253Z dev_airs-bp3.1.i80dhuud5hzd@node1    | 09/27 08:59:31.522: *****: [command.(*opSendResponse).DoSync:622]: number-type field «id_sales_area» is not found in type «untill.computers»: name not found
2023-09-27T08:59:31.523308137Z dev_airs-bp3.1.i80dhuud5hzd@node1    | number-type field «id_articles» is not found in type «untill.computers»: name not found
```
## Cause
9999999999 ID kept in the storage from old templates causes ID generator NextIDs collison
### initially, before #648:
- ID generator not considered IDs came with `c.sys.Init` and `c.sys.Import` commands
  - `c.sys.Init` with ID accidentally equal to the next Record ID according to the generator, then `c.sys.CUD` with a raw ID -> the `c.sys.Init` result is overwritten
- non-raw IDs from templates were sent with `c.sys.Init`
- records with non-raw IDs are stored in alpha
## after #648
- server starts
- 9999999999 ID is met in the storage on recovery
- internal `idGen.nextCDocCRecordBaseID` becomes 9999999999.BaseRecordID() +1 = 4999999999 +1 = 5000000000
- `IIDGen.NextID()` is called, result is ID 322690000000000
- ID 322690000000000 is stored
- server restarts
- 9999999999 ID is met in the storage on recovery again
- internal `idGen.nextCDocCRecordBaseID` becomes 9999999999.BaseRecordID() +1 = 4999999999 +1 = 5000000000
- 322690000000000 ID is met next
- internal `idGen.nextCDocCRecordBaseID` is not changed because 322690000000000.BaseRecordID() is 0!. ID gen decides that next 5000000000, but 0 is met -> next is still 5000000000 to avoid collisions according to #648
- `IIDGen.NextID()` is called, result is ID 322690000000000 again because `idGen.nextCDocCRecordBaseID` is still 5000000000
- existing record under ID 322690000000000 is overwritten
See the test describing the problem: https://github.com/voedger/voedger/blob/cbf1fec92fe1ec25fa17b9897261835c7aa6c017/pkg/istructsmem/idgenerator_test.go#L85 (will be skipped after fix)

## Situation in Alpha
- alpha contains records like 322685000131072+ (from the old algorythm), and 3226900000000000+ (after #648 ), and 32268500000000-322685000131072 (after #688)
  - existing records with "correct" IDs (ones that started from 322685000131072) will be overwritten one more last time after 131072 new records inserted
- wrong to use existong workspace in the alpha because existing records could be overwritten anyway after current fix

## Situation in RC
- there are records like 322685000131072+ only
- there are wrong IDs uploaded by `c.sys.Init`
- ID generator is not involved because it is `c.sys.Init` (old algorythm)
- something is uploaded by `c.sys.CUD` anyway on restaurant prepare
- first issued ID on the first `c.sys.CUD` is 322680000131072
- server restarts
- wrong IDs are met on recovery -> ID generator is updated with wrong baseIDs
- 322680000131072 is met on recovery -> ID generator is updated with the right baseID
- further IDs issual is correct
So it is safe to apply the suggested fix (wrong IDs will be ignored, correct IDs will be used)

## Solution
- do not use existing workspaces with broken records in Alpha anymore
- on recovery:
  - initially `nextBaseRecordID = 131072`
  - rec.ID < 322680000000000 -> the ID is from old templates -> do nothing
  - -> `nextBaseRecordID = rec.ID.Base() + 1`

note: wrong to ignore the ID if the ID is from an another register because the register is not considered on `NewCDocCRecordID()`.  E.g.:
  - 5000000000333
  - 5000000333
  - result is 322685000000333 in both cases

```[tasklist]
### Tasks
- [ ] https://github.com/voedger/voedger/issues/707
- [ ] https://github.com/voedger/voedger/pull/719
- [ ] https://github.com/voedger/voedger/issues/720
```

**Comment by host6** [comment]
```
2023-09-28T11:12:58.996077709Z dev_airs-bp3.1.mafa09t7r6nv@node1    | 09/28 11:12:58.995: ---: [router.requestHandler.func1:158]: serving  POST   /api/untill/airs-bp/140737488486405/c.air.LinkDeviceToRestaurant
2023-09-28T11:12:58.996301679Z dev_airs-bp3.1.mafa09t7r6nv@node1    | 09/28 11:12:58.995: ---: [vvm.provideIBus.func1:46]: request body:
2023-09-28T11:12:58.996383415Z dev_airs-bp3.1.mafa09t7r6nv@node1    |  {"args":{"DeviceToken":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJBcHBRTmFtZSI6InVudGlsbC9haXJzLWJwIiwiQmlsbFByaW50ZXIiOjMyMjY4NTAwMDEzMTE4MSwiRHVyYXRpb24iOjYwMDAwMDAwMDAwMCwiSXNzdWVkQXQiOiIyMDIzLTA5LTI4VDExOjEyOjQ5LjQ2NjA2NjcyN1oiLCJTYWxlc0FyZWEiOjAsIlNhbGVzTW9kZSI6MSwiVGFibGVOdW1iZXIiOjEsImF1ZCI6ImRldmljZS5saW5rRGV2aWNlUGF5bG9hZCIsImV4cCI6MTY5NTkwMDE2OSwiaWF0IjoxNjk1ODk5NTY5fQ.jhXhogy3kwCIoObu8cbjnWKJcHOKqV16P4DiidsiX2A","DeviceName":"emu64xa","DeviceProfileWSID":140737488486539}}
2023-09-28T11:12:58.997820007Z dev_airs-bp3.1.mafa09t7r6nv@node1    | 09/28 11:12:58.997: ---: [iauthnzimpl.GetComputersRecByDeviceProfileWSID:68]: device profileWSID 140737488486539 : computers[ 322690000000000 ] inactive
2023-09-28T11:12:58.999521134Z dev_airs-bp3.1.mafa09t7r6nv@node1    | 09/28 11:12:58.999: *****: [command.(*opSendResponse).DoSync:622]: int64-type field «device_profile_wsid» is not found in type «untill.courses»: name not found
```

**Comment by host6** [comment]
```
2023-09-28T14:01:40.868418501Z dev_airs-bp3.1.vk4qqn0jpd5q@node1    | 09/28 14:01:40.867: ---: [router.requestHandler.func1:158]: serving  POST   /api/untill/airs-bp/140737488486405/c.air.LinkDeviceToRestaurant
2023-09-28T14:01:40.870556089Z dev_airs-bp3.1.vk4qqn0jpd5q@node1    | 09/28 14:01:40.870: ---: [vvm.provideIBus.func1:46]: request body:
2023-09-28T14:01:40.870599070Z dev_airs-bp3.1.vk4qqn0jpd5q@node1    |  {"args":{"DeviceToken":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJBcHBRTmFtZSI6InVudGlsbC9haXJzLWJwIiwiQmlsbFByaW50ZXIiOjMyMjY4NTAwMDEzMTE4MSwiRHVyYXRpb24iOjYwMDAwMDAwMDAwMCwiSXNzdWVkQXQiOiIyMDIzLTA5LTI4VDE0OjAxOjMxLjA0MDUzNzI5NFoiLCJTYWxlc0FyZWEiOjAsIlNhbGVzTW9kZSI6MSwiVGFibGVOdW1iZXIiOjEsImF1ZCI6ImRldmljZS5saW5rRGV2aWNlUGF5bG9hZCIsImV4cCI6MTY5NTkxMDI5MSwiaWF0IjoxNjk1OTA5NjkxfQ.CYob_xpk7NVHnnx2-Fqi-F9yCGmQ-_SGqgbUzvElN2M","DeviceName":"emu64xa","DeviceProfileWSID":140737488486541}}
2023-09-28T14:01:40.883208846Z dev_airs-bp3.1.vk4qqn0jpd5q@node1    | 09/28 14:01:40.876: ---: [iauthnzimpl.GetComputersRecByDeviceProfileWSID:68]: device profileWSID 140737488486541 : computers[ 322690000000002 ] inactive
2023-09-28T14:01:40.883631235Z dev_airs-bp3.1.vk4qqn0jpd5q@node1    | 09/28 14:01:40.883: ---: [iauthnzimpl.GetComputersRecByDeviceProfileWSID:73]: device profileWSID 140737488486541 : restaurant_computers[ 322690000000003 ] inactive
2023-09-28T14:01:40.885204673Z dev_airs-bp3.1.vk4qqn0jpd5q@node1    | 09/28 14:01:40.885: *****: [command.(*opSendResponse).DoSync:622]: string-type field «name» is not found in type «untill.article_options»: name not found
2023-09-28T14:01:40.885243084Z dev_airs-bp3.1.vk4qqn0jpd5q@node1    | int64-type field «device_profile_wsid» is not found in type «untill.article_options»: name not found
```

**Comment by host6** [comment]
!!! has RC 5_000_000_000 IDs now?

**Comment by host6** [comment]
```
2023-09-29T08:13:23.568742206Z dev_airs-bp3.1.kqheq56rienj@node1    | 09/29 08:13:23.567: *****: [command.(*opSendResponse).DoSync:622]: referential integrity violation: record ID 322690000000000 referenced by untill.article_options.id_options is of QName untill.article_available whereas [untill.options] QNames are only allowed
```

**Comment by host6** [comment]
see also #718
