### ISSUE TITLE
appdef: add IStruct, IDoc & IRecord inheritance for structure types

### ISSUE THREAD

**Issue by mail2nnv** [voedger/voedger#709]
# Concept

See [Voedger Type System](https://github.com/voedger/voedger/issues/168)

There are structural types in the type inheritance hierarchy. These include all kinds of documents with records, and objects with elements.

**This structuring needs to be more clearly reflected in the inheritance hierarchy**.

# Now

The following structural types directly inherit from the abstract type `IType`: 
- `IGDoc` 
- `IGRecord` 
- `ICDoc` 
- `ICRecord` 
- `IWDoc` 
- `IWRecord` 
- `IODoc` 
- `IORecord` 
- `IObject` 
- `IElement`

# Must be

We need the structural types inheritance scheme shown in the following mermaid diagram.

```mermaid
classDiagram

    class IStructure {
        <<interface>>
        +Abstract() bool
        +Fields() []IField
        +Containers() []IContainer
        +Uniques() []IUnique
    }

    IDoc --|> IStructure : inherits
    class IDoc {
        <<interface>>
    }

    IGDoc --|> IDoc : inherits
    class IGDoc {
        <<interface>>
        ~Kind => TypeKind_GDoc
    }

    ICDoc --|> IDoc : inherits
    class ICDoc {
        <<interface>>
        ~Kind => TypeKind_CDoc
        +Singleton() bool
    }

    IWDoc --|> IDoc : inherits
    class IWDoc {
        <<interface>>
        ~Kind => TypeKind_WDoc
    }
                    
    IODoc --|> IDoc: inherits
    class IODoc {
        <<interface>>
        ~Kind => TypeKind_ODoc
    }

    IStructure <|-- IRecord  : inherits
    class IRecord {
        <<interface>>
    }

    IRecord <|-- IGRecord : inherits
    class IGRecord {
        <<interface>>
        ~Kind => TypeKind_GRecord
    }

    IRecord <|-- ICRecord : inherits
    class ICRecord {
        <<interface>>
        ~Kind => TypeKind_CRecord
    }

    IRecord <|-- IWRecord : inherits
    class IWRecord {
        <<interface>>
        ~Kind => TypeKind_WRecord
    }

    IRecord <|-- IORecord : inherits
    class IORecord {
        <<interface>>
        ~Kind => TypeKind_ORecord
    }

    IObject --|> IStructure : inherits
    class IObject {
        <<interface>>
        ~Kind => TypeKind_Object
    }

    IStructure <|-- IElement : inherits
    class IElement {
        <<interface>>
        ~Kind => TypeKind_Element
    }
```
```[tasklist]
### Tasks
- [x] add `IStruct`, `IDoc`, and `IRecord`
- [x] add `IAppDef.Structures()` iterator
- [x] add system fields to IRecord, IDoc
- [x] to avoid unwanted type assertion add non exported stub methods like isGDoc(), isWRecord(), etc…
```
