### ISSUE TITLE
refactor ctool

### ISSUE THREAD

**Issue by maxim-ge** [voedger/voedger#727]
```[tasklist]
### Tasks
- [x] Use hostname instead of IP addresses
- [x] Create script for rolling restart (replace node)
- [x] Test se-node replacement
- [x] Add support for ubuntu 22.04
- [x] Send PR
```
