### ISSUE TITLE
appdef: add IFunc ancestor for ICommand and IQuery

### ISSUE THREAD

**Issue by mail2nnv** [voedger/voedger#735]
# Concept

See [Voedger Type System](https://github.com/voedger/voedger/issues/168)

In the type hierarchy, the `ICommand` and `IQuery` interfaces have common members, but there is no common interface for their inspection.

**The common members of the `ICommand` and `IQuery` interfaces should be allocated to a common `IFunction` interface from which to inherit**.

# Now

The following functional types directly inherit from the abstract type `IType`: 
- `ICommand` 
- `IQuery` 

# Must be

We need the function-types inheritance scheme shown in the following mermaid diagram.

```mermaid
classDiagram
    class IType {
        <<interface>>
        +QName() QName
        +Kind() TypeKind
        +Comment() []string
    }

    IType <|-- IFunction : inherits
    class IFunction {
        <<interface>>
        +Extension() IExtension
        +Param() IObject
        +Result() IObject
    }

    IFunction <|-- ICommand : inherits
    class ICommand {
        <<interface>>
        ~Kind => TypeKind_Command
        +UnloggedParam() IObject
    }

    IFunction <|-- IQuery : inherits
    class IQuery {
        <<interface>>
        ~Kind => TypeKind_Query
        -isQuery()
    }

    IFunction "1" *-- "1" IExtension : has
    class IExtension {
        <<interface>>
        +Name() string
        +Engine() ExtensionEngineKind
        +Comment() []string
    }

    IExtension "1" ..> "1" ExtensionEngineKind : refs
    class ExtensionEngineKind {
        <<enumeration>>
        BuiltIn
        WASM
    }
```

**Rem**: In the above diagram the `Param` and `Result` of the function are `IObject`, in future versions it will be changed to an array of `[]IParam` and renamed to plural.

```[tasklist]
### Tasks
- [x] add `IFunction` to inherit `ICommand` and `IQuery`
- [x] add `IAppDef.Functions()` iterator
- [x] refactor `istructsmem/desc` package to describe app functions
```
