### ISSUE TITLE
Develop appdefcompat package

### ISSUE THREAD

**Issue by host6** [voedger/voedger#736]
## Requirements

A tool compares two versions of AppDef and check their compatibility. Schemas are compatible when all following conditions are met:
- All QNames from ast1 exist in the new ast2
- Fields set (except view keys)
  - order and type change denied
  - ~size decrease denied~
    - size decrease allowed because it is still able to read old long values
  - removal denied
  - existing tables, keys, types etc:
    - append non-required only only, no insert
    - become required denied
  - new tables, keys, types etc - no checks
- In Views:
  - Keys, Value: change denied
  - Key fields: any change denied
- Tables:
  - parent/child relationships not changed from ast1 to ast2
  - inheritance is not changed (e.g. CDoc->WDoc, non-singleton->singleton etc)
  - unique field add denied
- Projectors:
  - SYNC property not changed from ast1 to ast2
  - ON, STATE, INTENT - may change from ast1 to ast2!
- Commands:
  - Args, UnloggedArgs change denied
  - Result change allowed
- Workspaces:
  - new version can not become abstract
  - inheritance is not changed

### Context

- https://github.com/voedger/voedger/issues/167

## Design

ref. [README-compat.md ](https://github.com/voedger/voedger/blob/main/pkg/appdefcompat/README.md)
- [Development version](https://github.com/anurmanov/voedger/blob/617-parser-package-ast-compatibility-tool-1/pkg/appdefcompat/README.md)
```[tasklist]
### TODO
- [x] Implement CompareTrees
- [x] IgnoreCompatibilityErrors
- [x] Implement CompatibilityError.ErrorType
- [x] Test new table, type, command, query, view - allowed
- [x] Test view: key parts are nonmodifiable, view value - same rules as for table fields
- [x] Test commands: Args, UnloggedArgs and Result change denied
- [x] Test workspaces: becoming abstract denied
```

**Comment by anurmanov** [comment]
Inheritance is not implemented yet in appdef. So I skipped tests for this feature and added proper TODO section.
