### ISSUE TITLE
[epic] ctool: Backup/Restore

### ISSUE THREAD

**Issue by maxim-ge** [voedger/voedger#765]
## Motivation

- Restore **entire** cluster, e.g. after wrong upgrade

## Principles

- Backup/Restore all keyspaces but: "^(?!system)"
  - system_auth
  - system_distributed
  - system
  - system_traces
  - system_schema
  - system_distributed_everywhere
- Backup from one cluster node can not be used on another
  - [Documentation: scylladb backup](https://opensource.docs.scylladb.com/stable/operating-scylla/procedures/backup-restore/backup.html)
    - every node must have backup
  - [Restore procedure](https://opensource.docs.scylladb.com/stable/operating-scylla/procedures/backup-restore/restore.html)
    - The procedure restores each node using the backup file of the same node. If this is not the case, one should use other restoration methods tools like [sstableloader](https://opensource.docs.scylladb.com/stable/operating-scylla/procedures/cassandra-to-scylla-migration-process.html). This procedure is much slower than restoring to the same topology cluster
  - But if every node have full token range - it look possible...
- No incremental backups (yet)
- Backup structure
  - [Backup folder] # yyyymmddhhmm-backup
    - [keyspace1]
        - data.tar.gz
        - schema.cql
    - [keyspace2]
        - data.tar.gz
        - schema.cql

## Functional Design

- Cluster private key must be passwordless
- Backups are  kept in /mnt/backup/voedger
- ctool backup cron  # show cron params
- ctool backup cron '* * /24 * *'
- ctool backup cron -d # remove cron information
- ctool backup now # make db nodes backup now
- ctool backup list # show list of folder names and node names `<backup-folder-name> db-node1, db-node-2, db-node-3`
- ctool restore <backup-folder-name>

### Context

- [scylladb backup](https://opensource.docs.scylladb.com/stable/operating-scylla/procedures/backup-restore/backup.html)
- [scylladb restore](https://opensource.docs.scylladb.com/stable/operating-scylla/procedures/backup-restore/restore.html)

### Principles

- All ctool backup subcommands check /mnt/backup/voedger available space
- ctool is kept on each cluster node (by init/replace commands)
  - $HOME/ctool/ctool
  - $HOME/ctool/pkey
- `ctool backupnode <node-name> <target-path>`
  - When particular db-node backup is started/finished a signal file $HOME/ctool/.voedgerbackup is created/removed
  - Check that the target node is a db-node
- app-node-1 keeps crone schedule
- If app-node-1 is done crone schedule is recreated during `replace` using cluster.json- 
```[tasklist]
### Tasks
- [ ] https://github.com/voedger/voedger/issues/747
- [ ] https://github.com/voedger/voedger/issues/1038
- [ ] https://github.com/voedger/voedger/issues/985
- [ ] https://github.com/voedger/voedger/issues/1027
- [ ] https://github.com/voedger/voedger/issues/1295
- [ ] https://github.com/voedger/voedger/issues/1359
- [ ] https://github.com/voedger/voedger/issues/1398
- [ ] https://github.com/voedger/voedger/issues/1396
- [ ] https://github.com/voedger/voedger/issues/1397
- [ ] https://github.com/voedger/voedger/issues/1399
- [ ] https://github.com/voedger/voedger/issues/1395
- [ ] https://github.com/voedger/voedger/issues/1400
- [ ] https://github.com/voedger/voedger/issues/1491
- [ ] https://github.com/voedger/voedger/issues/1471
- [ ] https://github.com/voedger/voedger/issues/1472
- [ ] https://github.com/voedger/voedger/issues/1498
- [ ] https://github.com/voedger/voedger/issues/1518
- [ ] https://github.com/voedger/voedger/issues/1431
- [ ] https://github.com/voedger/voedger/issues/1685
- [ ] https://github.com/voedger/voedger/issues/1702
- [ ] https://github.com/voedger/voedger/issues/1597
- [ ] https://github.com/voedger/voedger/issues/1600
- [ ] https://github.com/voedger/voedger/issues/1742
```

```[tasklist]
### Extra
```
