### ISSUE TITLE
make .sql file be registered in an extension point instead of `FileSchemaAST`s

### ISSUE THREAD

**Issue by host6** [voedger/voedger#783]
now ready-to-use `parser.FileSchemaAST`s are inserted into apps.EPPackageSchemasASTs extension point. Need raw `.sql` files be inserted there instead of `parser.FileSchemaAST`. It is need to have ability to iterate over all registered .sql files to implement #777 

```[tasklist]
### Tasks
- [x] apps.Parse -> apps.RegisterSchemaFS (packageDir, fullyQualifiedPackageName (i.e. `sys`, `air`), embedFS)
- [x] buildSchemasASTs(): parse all files from embedFS before `parser.BuildPackageSchema`
- [x] update `airs-bp3`
```
