### ISSUE TITLE
ctool: run SEDockerStack and MonDockerStack

### ISSUE THREAD

**Issue by maxim-ge** [voedger/voedger#80]
## TODO

- [x] Update tdesign.md
- [x] init + apply: se + mon stacks
- [x] smoke test for se + mon 
  - @AlekseiPonomarev

`ctool replace`: later

## cluster.json

- DesiredClusterVersion + ActualClusterVersion
- DesiredNodeVersion + ActualNodeVersion

## ctool upgrade

- Check Cmd???
Updates DesiredClusterVersion and create DesiredNodeState for all nodes
- DesiredNodeState.Version = DesiredClusterVersion

## ctool replace

- Check cluster version, Cmd == ""
- Cluster.Cmd = "replace"
- Cluster.CmdData = `<old-IP> <new-IP>`
- Create Node.DesiredNodeState
  - DesiredNodeState.Version = ActualClustertVersion
  - DesiredNodeState.IP = <new-IP>

## DesiredNodeState, ActualNodeState

- Version
- IP

## Node

- DesiredState
- ActualState
- Control
  - Error
  - AttemptsNo
  - Info

## NodeControllerFunction

Works if: section DesiredNodeState exists

  - Optionally update docker
  - Assign ActualNodeVersion = DesiredClusterVersion
  - Remove DesiredNodeState

## ClusterControllerFunction

```go
if ActualClusterVersion != DesiredClusterVersion {
  DeploySwarm()
  UpdateSEDockerStack()
  UpdateDBScyllaDockerStack()
  UpdateMonDockerStack()
  return
}
if Cmd == "replace" {
  ???
  return
}
```
## ctool upgrade

**Comment by maxim-ge** [comment]
- [ ] Get rid of `force` mode
- [ ] Get rid of AttemptNo, Info
- [ ] naming: Errror* = Err*
