### ISSUE TITLE
Implement compatibility unit test in airsbp3/compat_test.go

### ISSUE THREAD

**Issue by host6** [voedger/voedger#844]
```[tasklist]
### Tasks
- [x] Fix baseline (apps)
- [x] Add unit test for baseline (key packages and files: apps.yaml must contain 4 apps and existance of the airs-scheme/bp3)
- [x] Reassemble baseline_schemas based on latest rc branch and appropriate voedger package
- [x] Fix NodeInserted compatibility error in appdefcompat package of the voedger project
```
