### ISSUE TITLE
describe commands and queries in sql in Air

### ISSUE THREAD

**Issue by host6** [voedger/voedger#845]
- note about tables overview:
```sql
TYPE TablesOverviewResult_History (
	ODocID ref NOT NULL,
	Record text NOT NULL
);
TYPE TablesOverviewResult (
	Offset int64 NOT NULL,
	WDoc text NOT NULL,
	History TablesOverviewResult_History
);
```
the object that describes `Histroy` output field must return its QName here: https://github.com/untillpro/airs-bp3/blob/64d6b56b1b8909c52e8bac2517d9b252d7efdeae/packages/air/tablesoverview/tablesoverview.go#L167 as defined in sql. So here : https://github.com/untillpro/airs-bp3/blob/64d6b56b1b8909c52e8bac2517d9b252d7efdeae/packages/air/tablesoverview/consts.go#L38 must be `TablesOverviewResult_History`, not `History`

```[tasklist]
### Tasks
- [x] `c.air.Order` (nested tables + need to use `untill` package in a workspace)
- [x] `c.air.NewProformaPrinted` (need to use `untill` package in a workspace)
- [x] `c.air.UpdateSubscription` (json func)
- [x] `q.air.TransactionHistory` -> `q.air.GetTransactionHistory`
- [x] `c.air.SaveUPEvent` (json func)
- [x] `c.air.SaveUPTerminalEvent` (json func)
- [x] `c.air.UPCapturePayment` (json func)
- [x] `c.air.SaveUPTransferEvent` (json func)
- [x] `c.air.CreateWorkspaceDailyUPReport` (odoc in arg)
- [x] `q.air.UPTerminalWebhook` (json func in and out)
- [x] `q.air.UPReportWebhook` (json func in and out)
- [x] `q.air.UPTransferWebhook` (json func in and out)
```

**Comment by host6** [comment]
https://github.com/untillpro/airs-bp3/commit/cfda052a09e170895b366e8ba7a0c68bb269a12c
