### ISSUE TITLE
bp3: Observe projectors (and other vvm parts) status...

### ISSUE THREAD

**Issue by maxim-ge** [voedger/voedger#866]
```[tasklist]
### Tasks
- [ ] https://github.com/voedger/voedger/issues/884
- [ ] https://github.com/voedger/voedger/issues/891
- [ ] https://github.com/voedger/voedger/issues/892
- [ ] https://github.com/voedger/voedger/issues/920
- [ ] Configure slack alert for projectors_in_error (ivv)
- [ ] https://github.com/voedger/voedger/issues/1262
- [ ] https://github.com/voedger/voedger/issues/1289
```
