### ISSUE TITLE
[epic] Uniques with multiple fields

### ISSUE THREAD

**Issue by maxim-ge** [voedger/voedger#867]
## Motivation

https://dev.untill.com/projects/#!663686
need to have an unique on a fields combination `From` and `Till` varchar fields of `wdoc.air.UPPayout`
Problems: 
- old uniques engine is not suitable because `From` and `Till` are both varchar fields. Only one varchar field in one unique is allowed

## Functional Design

```sql
TABLE TablePlan INHERITS CDoc (
    FState int,
    Name varchar NOT NULL,
    ...

    UNIQUE (FState, Name), -- unnamed UNIQUE table constraint, parser generates unique QName `main.TablePlan$uniques$01` automatically
    CONSTRAINT UniqueTable UNIQUE (TableNumber), -- named UNIQUE table constraint. Parser generates unique QName `main.TablePlan$uniques$UniqueTable` automatically
    UNIQUEFIELD Name, -- deprecated. For Air backward compatibility only. No according `IUnique` is generated
)
```

## Technical Design

We can use existing Uniques view

## Context

- sql: `UNIQUE (fld1, fld2)`: https://github.com/voedger/voedger/blob/0f6794ba83c822a7105b293b00e20abb74150ad8/pkg/parser/sql_example_app/pmain/package.sql#L78
- #151 

```[tasklist]
### Tasks
- [ ] https://github.com/voedger/voedger/issues/1096
- [ ] https://github.com/voedger/voedger/issues/1097
- [ ] https://github.com/voedger/voedger/issues/1125
- [ ] https://github.com/voedger/voedger/issues/1160
- [ ] https://github.com/voedger/voedger/issues/1222
- [ ] update doc at https://dev.heeus.io/launchpad/#!25926
- [ ] https://github.com/voedger/voedger/issues/1210
```

**Comment by host6** [comment]
- null==0==""
- insert null, then insert 0 -> error
- no case when the unique field value is set for the first time on update
- discuss with Yougin: what to do if `DisplayName` is unkonown on insert 
- unique fileds must be required

**Comment by host6** [comment]
```sql
VIEW Uniques (
	QName qname NOT NULL, -- QName of the doc the values are from.
	ValuesHash int64 NOT NULL,
	Values bytes(32768) NOT NULL,
	ID ref,
	PRIMARY KEY ((QName, ValuesHash) Values)
) AS RESULT OF ApplyUniques;
```
- byte(0) is added at the beginning of each `varchar` or `bytes` field value
  - need to handle empty strings and bytes
-
