### ISSUE TITLE
Rate Limits

### ISSUE THREAD

**Issue by maxim-ge** [voedger/voedger#868]
Migrated to #3228 

## Related Work

- Rates, https://dev.heeus.io/launchpad/#!18866
```[tasklist]
### Tasks
- [ ] https://github.com/voedger/voedger/issues/1127
- [ ] https://github.com/voedger/voedger/issues/1962
- [ ] https://github.com/voedger/voedger/issues/1346
- [ ] https://github.com/voedger/voedger/issues/1354
- [ ] https://github.com/voedger/voedger/issues/1361
- [ ] https://github.com/voedger/voedger/issues/1363
- [ ] https://github.com/voedger/voedger/issues/1370
- [ ] https://github.com/voedger/voedger/issues/1372
- [ ] https://github.com/voedger/voedger/issues/3020
- [ ] https://github.com/voedger/voedger/issues/2907
- [ ] https://github.com/voedger/voedger/issues/2908
- [ ] https://github.com/voedger/voedger/issues/3005
- [ ] https://github.com/voedger/voedger/issues/3134
- [ ] https://github.com/voedger/voedger/issues/3136
- [ ] https://github.com/voedger/voedger/issues/3006
- [ ] https://github.com/voedger/voedger/issues/2999
- [ ] https://github.com/voedger/voedger/issues/3094
- [ ] https://github.com/voedger/voedger/issues/3096
```

```[tasklist]
### Tasks
- [ ] bomber
- [ ] BO User shall not add sales
```
