### ISSUE TITLE
ctool: refactor `replace` operation

### ISSUE THREAD

**Issue by maxim-ge** [voedger/voedger#968]
## Problem

- If db-node is up replace fails
- If replace fails then repeat also fails if new node is cleaned up
```[tasklist]
### TODO
- [x] Check that node being replaced is inactive
- [x] Add "ReplacedAddresses": [ "5.255.255.61", "5.255.255.62", "5.255.255.64"]
- [x] Avoid using addresses mentioned in ReplacedAddresses
- [x] Use `replace db-node-1 <address>` syntax
- [x] Remove "DataCenters"
- [x] Actualize tdesign.md, use javascript language
- [ ] Test "Avoid using addresses mentioned in ReplacedAddresses" using execRootCmd
```
