### ISSUE TITLE
appdef: Projector can be triggered by command argument type

### ISSUE THREAD

**Issue by maxim-ge** [voedger/voedger#993]
# Concept

### existing syntax
 
```sql
    -- Projector triggered by speciied command with «AddSubscription» name
    PROJECTOR UpdateSubscriptionProfile
        AFTER EXECUTE ON Subscript;
```

### new syntax
 
```sql
    -- Projector triggered by any command with argument «SubscriptEvent» type
    PROJECTOR UpdateSubscriptionProfile
        AFTER EXECUTE WITH SubscriptEvent;
```

# TODO:

```[tasklist]
- [x] Add `ProjectorEventKind_ExecuteWithParam` enum value
- [x] project builder should accept for execute with param only objects and odocs
- [x] update `istructsmem/descr` package
- [x] update tests, examples, README etc…
```

**Comment by mail2nnv** [comment]
Also in this issue is solved #958 https://github.com/voedger/voedger/issues/958

**Comment by mail2nnv** [comment]
## Technical debt:

After task #994 is closed, the description of the projectors should be corrected:
- `pkg/sys/sys.sql`:
  - [ ] RecordsRegistryProjector
  - [ ] ProjectorWLogDates
  - [ ] ApplyUniques
- `pkg/parser/sql_example_app/vrestaurant/package.sql`:
  - [ ] UpdateTableStatus
  - [ ] UpdateSalesReport
